### ISSUE TITLE
Add the ability to archive a task

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#1006]
# Problem

We need to add the ability to archive a task.

- Add an `archived` column to tasks

**Comment by begedin** [comment]
Needs

- add migration which adds `:archived` field, type of `:boolean`, `null: false`, default: `false`
- add field to `Task` model
- cast `:archived` as part of the `Task.update_changeset/2`
- modify tests for `Task.update_changeset/2`

Total estimate ~2 hours
