### ISSUE TITLE
Filter tasks by archived status

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#1007]
# Problem

- Add a filter to return tasks based on whether they are archived
- Default for returning tasks is _not_ archived

**Comment by begedin** [comment]
We should modify `Task.Query.list/2` for this.

This introduces an optional filter with a default. What our private `do_list` functions are doing at the moment is that they apply optional filters without a default.

I'm thinking we should rename them into `apply_optional_filters`.

In `Task.Query`

- rename `do_list` to `apply_optional_filters`
- add `apply_archived_status(query, params)`,  which, if `params` contain `archived`, apply the value of `archived`. If not, they apply the default value of `archived: false`.
- call this new function from `list/2`, before or after `apply_optional_filters`

Also 
- add `Task.Query` tests to ensure this new behavior

Total estimated ~3 hours

**Comment by begedin** [comment]
Blocked by #1006
