### ISSUE TITLE
Discussion issue: Figure out background processing

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1030]
# Problem

Merging #1022, even though I did not observe this behavior when testing the PR, somehow now causes tests to output errors due to background tasks remaining active AFTER the test that spawned them exists. 

The tests themselves still pass, and this on itself does not always happen (only most of the time), but this is likely behavior we want to avoid for a multitude of reasons. It pollutes output, may cause unexpected behavior in the future and overall is an indicator our background processing setup is, at the very least, suboptimal.

Finding the tests that cause this and adding `wait_for_supervisor()` into them DOES NOT solve the problem. All it does is, it switches the unreliable behavior to the opposite - the tests now just as often fail to wait properly (because the async process is already done by the time the test tries to wait) as they were outputting the errors before.

It seems like there is a timing window which is so narrow that, when the `wait_for_supervisor` is called, the background task executes before `wait_for_supervisor` is able to monitor the process. 

On  the other hand, when `wait_for_supervisor` is not called, our checked out db connection closes before the background task completes.

We could try spending time fixing this as is, but really, our setup for background processing needs work anyway, so I think our logical options are

- Learn about OTP and implement a proper setup which we can keep track of and properly test. Possibly a gen_server could work.
- Make use of an existing library and implement that

## Existing libraries

https://github.com/akira/exq is sort of like Sidekiq and uses Redis. The readme itself advises the user to make sure this is actually what they need, since it's basically pushing Ruby behavior into Elixir, so I'm apprehensive about using that one.

https://github.com/joakimk/toniq is similar.

https://github.com/c-rack/quantum-elixir Uses a cron-based approach, but really is still quite similar. The difference is, it does not use redis on itself, so we'd have to implement some sort of task storage ourselves.

## Our own implementation

The following link describes a relatively simple implementation of a GenServer which periodically performs an action

https://hackernoon.com/background-processing-using-elixir-genserver-and-the-erlang-queue-class-8d476d4942c2 

## Actual problem

Really, what we need to resolve here is

- We need some way to schedule a task, with the ability to recover it in case of an error. Exq and Toniq use Redis for this automatically. With Quantum or our own implementation, we'd have to agree on a format and persist a record somehow. This could be a table in our own database or it could also be redis, or just be kept on the GenServer, though that isn't actually properly persisted.

- We need a worker which, periodically, or as often as possible takes a scheduled task and executes it.

- We need to rewrite our tests to get rid of `wait_for_supervisor`. Instead, the tests that use this function just schedule the correct job
- We need to write tests for the code which is being executed inside of jobs, to ensure that code, when executed synchronously, does what it needs to do. Some of that is already written, but we need more.

@JoshSmith We need to work this out and start implementing, probably sooner rather than later.

### Example of a very basic job scheduler

```Elixir
defmodule MyApp.Periodically do
  use GenServer

  def start_link do
    GenServer.start_link(__MODULE__, %{})
  end

  def init(state) do
    schedule_work() # Schedule work to be performed at some point
    {:ok, state}
  end

  def handle_info(:work, state) do
    # Do the work you desire here
    schedule_work() # Reschedule once more
    {:noreply, state}
  end

  defp schedule_work() do
    Process.send_after(self(), :work, 2 * 60 * 60 * 1000) # In 2 hours
  end
end

worker(MyApp.Periodically, [])
```

**Comment by joshsmith** [comment]
I think this is closeable because the problem was really caused by how we were handling `Task.Supervisor` processing in testing.
