### ISSUE TITLE
Refactor tests to not rely on ENV vars

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#109]
We have some tests, like photo uploads, that rely on secret ENV vars. We should allow people to run tests excluding these.

This will require updating the README and adding some config to the tests.

**Comment by joshsmith** [comment]
@green-arrow what else do we need to do to consider this closed?

**Comment by green-arrow** [comment]
I think we should be able to consider this closed since we have a pattern down now for excluding those kinds of tests.
