### ISSUE TITLE
Implement GitHub.API.Repository module

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1109]
# Problem

#1107 will allow us to implement a  `GitHub.API.Repositories` module with, initially, an `issues(GithubRepo.t)` function which fetches all issues for a github repository.

Considering how we want to deal with our syncing, we may want the function return a stream instead of a loaded list.

This is blocked until we actually implement #1107

**Comment by joshsmith** [comment]
This is no longer blocked by #1107 because it's done in #1113
