### ISSUE TITLE
Implement GitHub.API.Issue.comments(GithubIssue.t)

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1110]
# Problem

In order to perform the comments step of syncing a github repository to codecorps, we need to implement `GitHub.API.Issue.comments(GithubIssue.t)`. It accepts a `GithubIssue` and returns the list of comments for that issue.

This depends on the implementation in #1107

**Comment by joshsmith** [comment]
I'm closing this because I think it's not needed. We'll fetch the comments all at once with #1111.
