### ISSUE TITLE
Installation repositories event does not pull in some data

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#1117]
# Problem

When we receive the `installation_repositories` event, we are unfortunately not pulling in some data about the repository, including:

- `github_account_id`
- `github_account_login`
- `github_account_avatar_url`
- `github_account_type`

This data _is_ available in the `installation`'s `account` object.

I'm wondering if we should simply defer to the installation's data on this and instead remove the `github_account_` details from the repos themselves.

**Comment by begedin** [comment]
Correct me if I'm wrong, but we don't actually use the account data from the repo anywhere. On ember, we render the installation data, next to the installation, but the repos are relatively simple list items in comparison.

I guess if we sync project with repos across multiple installations, we will then have to render these icons next to the repo itself on other pages (the task page, for example), but that should not be a huge deal.

I would be ok with ditching these fields and relying on installation fields instead.

I would put an estimate at ~1 hour to remove them from the API and potentially another 0.5-1 hour to  clean it up on ember (depending on us just needing to remove the fields from the model or having to do slightly more).

What do you think @JoshSmith ?

**Comment by joshsmith** [comment]
This data is actually used for presenting the details of it, which is how it was discovered.
