### ISSUE TITLE
Consider removing ProjectGithubRepo in favor of project_id on GithubRepo

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#1191]
# Problem

We've now made it 1:1 for `GithubRepo` to `Project`. I vote that we remove `ProjectGithubRepo` in favor of a nullable `project_id` foreign key on `GithubRepo` and adding a `has_many: :github_repos` to `Project`.

For this to work, we'll need to:
  - migrate the data from `ProjectGithubRepo` records over to `GithubRepo` records
  - add the sync state changes to `GithubRepo`
  - our syncing behavior will also change to remove references to `ProjectGithubRepo` and rely solely on `GithubRepo` and its `Project` relationship
  - client will need to change for this to work

We should also consider making the process of disconnecting from a repo not simply unset the `project_id` but instead set a boolean value on whether it is/isn't synced. This allows us to keep track of projects that were previously synced and possibly overcome any issues that would occur when a project is unsynced.

Probably we should even get an email when such an unlinking happens because I'm not sure we're prepared to handle it.

**Comment by joshsmith** [comment]
We'll need to add:

- Segment tracking again for the connection
- Controller test for connecting the project

**Comment by snewcomer** [comment]
This all makes sense.  Unsetting the project_id will essentially create a `dead` GithubRepo model so yeah it might be nice to keep that around.

**Comment by joshsmith** [comment]
Closed by #1194
