### ISSUE TITLE
Filter users by username and project

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#1214]
# Problem

Right now we can filter users by username, but we cannot further limit that with a JOIN of `projects`.

We want to be able to pass in a `project_id` to the user search endpoint and restrict the query to users in that project only.

**Comment by vishaldeepak** [comment]
Which api is this specifically? Are we talking about `users/username_available`?

**Comment by joshsmith** [comment]
No this is filtering on the users endpoint. The index.

**Comment by joshsmith** [comment]
@begedin I think we need to open a follow up issue on Ember (if there isn’t already one) to add the filtering to the typeahead.
