### ISSUE TITLE
When creating a Project, we do not create an associated ProjectUser record

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1282]
# Problem

Right now, our project create endpoint authorizes creation by verifying that the project's organization is owned by the current user.

Then, it simply creates a `Project` record with the usual associations (task lists), but creates no associated `ProjectUser` record of role `"owner"`.

We can technically still infer that a `User` is an __owner__ of a `Project` by checking the organization owner, but it seems unintuitive to me and our client does not seem to act this way - when we visit the page of a `Project` we've just created, we have the option to __join__ as if we're not a member.

## Option A

- [ ] `Project.create_changeset` creates a `ProjectUser` record as part of, for example, `prepare_changes`

## Option B

- [ ] `Projects.create` creates a `ProjectUser` as part of a multi

## Option C

- [ ] We keep things as is and instead, rewrite policies/client/etc. to also check organization owner

I'm leaning strongly against option C and moderately towards option B.

The reason I'm favoring option B and not A is because the same function may then, at a later time, be used to allow creation of projects by admins.

We would have to change the function signature to provide the current user, though.

**Comment by joshsmith** [comment]
I vote B.

**Comment by vishaldeepak** [comment]
There already seems to be a function `put_member_assoc` in `project.ex` which is part of the changeset,  that seems to be creating a project_user on creation of a project. ?

**Comment by joshsmith** [comment]
Is it possible that changeset is not being used when a project is created right now?

**Comment by vishaldeepak** [comment]
It is being used in `CodeCorps.Projects.create`via `Project.create_changeset` . The only place I can find where its not being used is in a seed file `AddDefaultTasksToProjects` where it uses only `Project.changeset`. 
I wrote the `Multi` method of creating `Project_User` on project creation. Only to find a test `test/lib/code_corps_web/controllers/project_controller_test.exs:94` was failing because `Project_User` is already being created.

**Comment by joshsmith** [comment]
Oh, hm.

@begedin can you please clarify this? You came across this problem so I'm not sure if maybe it was fixed without you realizing it?

**Comment by begedin** [comment]
I'm not sure when it was resolved, but I'm certain it was at some point during the last milestone or two. I distinctly remember trying to create a project in the new UI and ending up with a project I was not a member off. 

Either that, or something went strangely wrong.

**Comment by joshsmith** [comment]
@begedin so you consider it to be resolved now then?

**Comment by begedin** [comment]
@joshsmith @vishaldeepak 

Not much else to do about it. The API already does what it needs to do. Might have been my mistake, or maybe there was a bug of some sort but until/if it reappears, no reason to keep this open.

**Comment by begedin** [comment]
I just doublechecked and yes, I no longer have this issue. Still not sure if it was simply a fluke or has been fixed since, but definitely safe to remain closed.
