### ISSUE TITLE
Implement realtime updates of messages with client via channels

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#1284]
# Problem

From https://github.com/code-corps/code-corps-api/issues/1234#issuecomment-349187243

The idea behind the messaging feature is that it ought to work mostly in realtime, while still supporting async communication.

In order to achieve that, we need to be able to update both sides of the conversation about any changes to it in real time.

The most obvious approach to achieve that would be the phoenix channel feature.

**Comment by joshsmith** [comment]
Closed by #1301
