### ISSUE TITLE
 Add cat enum field to RoleSkill

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#129]
We're missing the cat enum field for `RoleSkill`.

For #26.

**Comment by npendery** [comment]
@JoshSmith what exactly does this do? I found something that I think we could use for it https://github.com/gjaldon/ecto_enum

**Comment by joshsmith** [comment]
@npendery we've just been using `validate_inclusion` and treating the column as a string for now. Maybe later we can circle back and add database-level integrity by using PG's `enum` or something like this.
