### ISSUE TITLE
Add full_name to user and its view

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#145]
The front-end expected a `full_name` which is not currently present on the model. This is a virtual composite of `first_name` and `last_name` for easier rendering by the client.

**Comment by schippada** [comment]
I modified the index action as below. I see the map is updated with the full_name attribute.  But the render method is not rendering the full_name attribute. It may that the render method is using the **struct** attribute to identify the attributes to render 
Can someone tell me how to solve this?

def index(conn, params) do
   users =
     User
     |> User.index_filters(params)
     |> preload([:slugged_route, :categories, :organizations, :roles, :skills])
     |> Repo.all
     |> add_full_name

   IO.inspect users
   render(conn, "index.json-api", data: users)
 end

 def add_full_name(users) do
   Enum.map(users, fn user -> Map.put_new(user, :full_name, user.first_name <> " "<> user.last_name) end)
 end

 [%{**meta**: #Ecto.Schema.Metadata<:loaded, "users">,
 web_1            |    **___struct__: CodeCorps.User_**, admin: false, base64_photo_data: nil,
 web_1            |    biography: nil, categories: [], email: "schippada@gmail.com",
 web_1            |    encrypted_password: "Welcome3", first_name: "Sreeni",
 web_1            |    full_name: "Sreeni Chippada", id: 1,
 web_1            |    inserted_at: #Ecto.DateTime<20016-09-11 01:00:00>, last_name: "Chippada",
 web_1            |    organization_memberships: [], organizations: [], password: nil, photo: nil,
 web_1            |    roles: [], skills: [], slugged_route: nil, state: "signed_up",
 web_1            |    state_transition: nil, twitter: nil,
 web_1            |    updated_at: #Ecto.DateTime<20016-09-11 01:00:00>, user_categories: [],
 web_1            |    user_roles: [], user_skills: [], username: "schippada", website: nil}]

**Comment by joshsmith** [comment]
@schippada I think this approach is not quite where you'd want to head.

What I would consider doing instead is tackling this in the user view, and having a `name` (not, `full_name`, that's my mistake!) that simply concatenates the `first_name` and `last_name` strings.

By running `Enum.map` here you'd have to apply that anywhere you'd want access to the `name`, which is too duplicative.

Writing this code in the user view also allows you to test that this works directly in your user view test, isolating the testing portion of it to one place only.

I would expect that the entire function definition and test will add no more than 4-5 lines of code total.

**Comment by schippada** [comment]
Thanks @JoshSmith  for the clarification. It was simple and now I am able to render the name attribute. But the test is failing. I added the name attribute to the expected_json as  "name" => user.first_name <> " " <> user.last_name. This is throwing the following error.

I am running test as:
[~/opt/dev/workspace/code-corps/code-corps-api → develop]$ mix test
What am I doing wrong.?

ERROR: 

 1) test renders email when user is the authenticated user (CodeCorps.UserViewTest)
     test/views/user_view_test.exs:86
     *\* (ArgumentError) argument error
     stacktrace:
       :erlang.bit_size(nil)
       (code_corps) web/views/user_view.ex:33: CodeCorps.UserView.name/2
       lib/ja_serializer/dsl.ex:95: anonymous fn/4 in JaSerializer.DSL.default_attributes/3
       (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
       (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
       lib/ja_serializer/dsl.ex:95: JaSerializer.DSL.default_attributes/3
       lib/ja_serializer/builder/attribute.ex:7: JaSerializer.Builder.Attribute.build/1
       lib/ja_serializer/builder/resource_object.ex:23: JaSerializer.Builder.ResourceObject.build/1
       lib/ja_serializer/builder/top_level.ex:24: JaSerializer.Builder.TopLevel.build/1
       lib/ja_serializer.ex:59: JaSerializer.format/4
       test/views/user_view_test.exs:94: (test)

**Comment by joshsmith** [comment]
@schippada a pull request on this issue would really help. It's hard to comment without actually being able to see the code.

**Comment by npendery** [comment]
@schippada, following up on @JoshSmith's comment. If you want to put up a PR we can help fix the error more efficiently.

**Comment by schippada** [comment]
@npendery , I fixed the issue as per Josh's suggestion and then created the pull request. I will connect with you tomorrow and will resolve this.
