### ISSUE TITLE
Reorganize model/controller helper code

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#155]
Taken from discussion in #139 

It looks like the functions we have there would fit into something like `CodeCorps.Slugs` and `CodeCorps.Filtering` more so than the current `CodeCorps.ControllerHelpers` and `CodeCorps.ModelHelpers` naming/organizational scheme.

Actual naming and organization is open for discussion, of course.

**Comment by joshsmith** [comment]
Some progress was made on this in #332 but could be refined further.

**Comment by joshsmith** [comment]
In particular would like to move most of what's in the model helpers into query helpers, but eventually replace even most of those with filters that primarily use filtering in `ja_resource` or something.
