### ISSUE TITLE
Simplify organization membership permissions

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#157]
See #149.

Find a way to provide a changeset, or params to `load_and_authorize_resource`when authorising the `:create` action. We need it in some cases, because in order to decide if the user is allowed to perform the action, we need to see what type of resource is being created. It is needed for: 
- `organization_membership` - User can only **create** their own pending membership and they should not be able to do it if they're already a member. The part of it being their own is handled by not allowing a `member_id` as a parameter. Instead, we just assign the current user. For **update**, we've simplified the permissions compared to rails, but ideally, we need to check what the current membership role is, and what we want it to be, then we want to decide if the user can do it based on their own role.
- `posts` - Any user, regardless of membership, can create ideas and issues. Other posts can only be created by contributors or higher.
- `project, project_category, project_skill` - We need to pass in the changeset so we can know which organization the record is being created for, since only some roles can do it.
- `user_category, user_role, user_skill` - These might actually be fine. We need to check to see if the user is modifying their own record on create. We could handle that without permissions, by doing it on the changeset.

**Comment by joshsmith** [comment]
This needs significant clarification now.

**Comment by begedin** [comment]
We already have a way to do changeset-based authorization, so this was probably supposed to be closed a while ago. I'm not completely clear on how the new memberships will work in conjunction with this, though.

We should probably step through the system one more time and list what people can and cannot do the way it is right now, as well as how it's supposed to be.

**Comment by joshsmith** [comment]
@begedin I'll close but can you create a follow-up issue for that?

**Comment by begedin** [comment]
Created #725
