### ISSUE TITLE
There is undeterminism in one of the pagination tests

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#170]
This happened to me only once, but we need to make the test deterministic:

```

1) test pagination specifying a page number works (CodeCorps.PostControllerTest)

test/controllers/post_controller_test.exs:221
  Assertion with == failed
  code: String.to_integer(id) == post_to_test.id()
    lhs:  4947
    rhs:  4949
    stacktrace:
      test/controllers/post_controller_test.exs:237: (test)
```

**Comment by noslouch** [comment]
I wrote that test. Can we specify the IDs of the fake posts at insert-time?

**Comment by joshsmith** [comment]
@begedin is this still an issue? I've never seen it.

**Comment by begedin** [comment]
@JoshSmith I had it occur once or twice yesterday, so yes, still on.

**Comment by joshsmith** [comment]
Really? I have never once seen this, particularly not in CI. That's really odd.

Any ideas on how to fix?

**Comment by begedin** [comment]
Looking at it, it should be fine now, since we're ordering posts explicitly by newest first.

Possibly, some other test is non-deterministic now and I just dismissed it yesterday, assuming it was this one. I would close this. I'll open another one if I see it happening again.

**Comment by joshsmith** [comment]
Reopening because this just happened for me:

```
  1) test pagination specifying a page number works (CodeCorps.TaskControllerTest)
     test/controllers/task_controller_test.exs:268
     Assertion with == failed
     code: String.to_integer(id) == task_to_test.id()
     lhs:  2807
     rhs:  2808
     stacktrace:
       test/controllers/task_controller_test.exs:284: (test)
```

**Comment by noslouch** [comment]
So should the ID be set in the test then? I can update so it's always the
same int, but then I worry about conflicting with previously generated IDs

**Comment by joshsmith** [comment]
@noslouch I'm honestly not sure the best approach here. I would also worry about the conflict.

**Comment by joshsmith** [comment]
@noslouch we may want to ask the folks who wrote Scrivener Ecto? They would probably have run into this...

**Comment by joshsmith** [comment]
Closing since we don't paginate tasks now.
