### ISSUE TITLE
Add tests for all of our authorization policies

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#174]
If this turns out to bee too big for a single PR, feel free to create individual issues and tackle them separately
- [x] Category
- [x] Comment
- [x] Organization
- [x] OrganizationMembership
- [x] Preview
- [x] Project
- [x] ProjectCategory
- [x] ProjectSkill
- [x] Role
- [x] RoleSkill
- [x] Skill
- [x] Task
- [x] User
- [x] UserCategory
- [x] UserSkill
- [x] UserRole

**Comment by wolverineks** [comment]
is this still open? it looks like there are auth tests in the CategoryController already.

**Comment by joshsmith** [comment]
@wolverineks explicit unit tests for the policies, not in the controllers. Allows us to do more edge case testing.

**Comment by joshsmith** [comment]
Blocked #157.

**Comment by joshsmith** [comment]
@begedin marked in progress due to work you're doing in #320
