### ISSUE TITLE
Determine what policies we had in Rails that are needed in Phoenix

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#175]
There are some policies we have in rails, which we do not in phoenix, such as `post_image`, `comment_image`, etc. 

Some of these are missing simply due to not being implemented yet, while some, we do not really need either because there is no endpoint for them or the endpoints are all public.

```
comment_image_policy.rb
comment_user_mention_policy.rb
github_repository_policy.rb
import_policy.rb
import_skill_failure_policy.rb
post_image_policy.rb
post_like_policy.rb
post_user_mention_policy.rb
preview_user_mention_policy.rb
project_role_policy.rb
slugged_route_policy.rb
```

**Comment by joshsmith** [comment]
@begedin I've forgotten the context for this and it's not clear what needs discussed; can you clarify?

**Comment by begedin** [comment]
These pundit policies are explicitly defined in rails but we do not have or use them for anything in phoenix right now.

I don't think we actually need them, but I wanted to compile a list, so I get get your view on it and we actually do need any of these. If not, feel free to close.

**Comment by joshsmith** [comment]
These are not needed!
