### ISSUE TITLE
Break out "model" tests that hit the database into Repo tests?

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#178]
I think in a number of our "model" tests we're hitting the database, which means that they are certainly not side-effect free. It looks as though the convention appears to be to break these tests out into Repo tests, like `UserRepoTest`.

Would like to hear thoughts on this.

**Comment by wolverineks** [comment]
my understanding was that separating the tests would allow more fine-grain control on which tests could be asynchronous. but with ecto 2.0, you can run your database tests async with their 'sandbox' feature. this seems to make the separation a moot point

[ecto 2.0 allows concurrent tests that hit the database](http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/)

**Comment by joshsmith** [comment]
Ah, okay, that makes sense @wolverineks. Does that mean that you can also run async controller tests, or is there something else about that which prevents similar behavior? (I did not RTFM)

**Comment by wolverineks** [comment]
I don't see why not, but haven't used it myself.

**Comment by joshsmith** [comment]
Does that mean that we need to explicitly set the test as `async`? What's the reason for any explicitness there if Ecto does this automatically now?

**Comment by joshsmith** [comment]
@wolverineks bump.
