### ISSUE TITLE
Docker-compose up --build not working locally

### ISSUE THREAD

**Issue by npendery** [code-corps/code-corps-api#183]
When trying to set up with: `docker-compose up --build` I am getting the error:

```
04:18:13.334 [error] SSL: :certify: ssl_handshake.erl:1539:Fatal error: certificate expired

Registry update failed (http_error)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:tls_alert, 'certificate expired'}}]}
```

**Comment by snewcomer** [comment]
I did not get an error.  On docker 1.12.0-a fyi

<img width="1440" alt="screen shot 2016-09-10 at 8 58 32 am" src="https://cloud.githubusercontent.com/assets/7374640/18411822/cc85f7a4-7734-11e6-9548-ded23deb0632.png">

**Comment by npendery** [comment]
Tried on my work computer and I do not get an error, only my personal one. Since this is probably just an isolated bug, I dont think we need an issue.
