### ISSUE TITLE
Remove Phoenix built in PageController

### ISSUE THREAD

**Issue by npendery** [code-corps/code-corps-api#198]
We need to get rid of the page that renders for the main api page: https://api.pbqrpbecf.org/

[Router endpoint](https://github.com/code-corps/code-corps-phoenix/blob/develop/web/router.ex#L27)

**Comment by joshsmith** [comment]
@npendery agreed but not sure what the replacement is. Was thinking we could do something like the `/ping` endpoint here instead?

**Comment by npendery** [comment]
Yeah that would be a good replacement
