### ISSUE TITLE
Add Mailchimp signup to signup flow

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#235]
We had this in the Rails API. We should add here to ensure people who sign up are in our email list.

**Comment by vidmantas** [comment]
I'll try to do it. Can I use https://hex.pm/packages/mailchimp as a new dependency? I don't quite like it as it doesn't have a proper test coverage, but was unable to find anything better.

**Comment by joshsmith** [comment]
@vidmantas that's fine, I think. Do you want to open an issue over there re: the test coverage?

**Comment by vidmantas** [comment]
@JoshSmith okay, good suggestion. I'll try to do the integration first to make sure it's really something we can rely on.
