### ISSUE TITLE
docker-compose up --build failing

### ISSUE THREAD

**Issue by schippada** [code-corps/code-corps-api#246]
Error:
web_1            | == Compilation error on file lib/phoenix_live_reload/live_reloader.ex ==
web_1            | *\* (File.Error) could not read file "/code-corps-api/_build/dev/lib/phoenix/priv/static/phoenix.js": no such file or directory
web_1            |     (elixir) lib/file.ex:244: File.read!/1
web_1            |     lib/phoenix_live_reload/live_reloader.ex:56: (module)
web_1            |     (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
web_1            |
web_1            | could not compile dependency :phoenix_live_reload, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix_live_reload", update it with "mix deps.update phoenix_live_reload" or clean it with "mix deps.clean phoenix_live_reload"

**Comment by joshsmith** [comment]
@schippada have you been trying to build your app both locally and via Docker? Can you try doing (from your Elixir app's root directory) `rm -rf ./build`? It's possible you've tried compiling on your host machine and your app is now attempting to use `./build` compiled resources on Docker, which is an entirely different architecture.

**Comment by schippada** [comment]
@JoshSmith , I am trying to build locally. Just to be sure, I removed all images. Also removed all stopped images. There is no .build folder in the app directory.

**Comment by joshsmith** [comment]
@schippada there's definitely a `/build` dir in your project root. You've built via Docker and now you're building with another platform. That's the problem, almost certainly.

Try the above and try again. Just removing Docker images will not fix this.

**Comment by schippada** [comment]
Hi Josh, I removed my project folder and cloned again. I am not sure if that is what is causing the problem. I am not sure where the ./build folder is created.

**Comment by joshsmith** [comment]
@schippada there's also a `deps` directory.

See http://stackoverflow.com/questions/39562118/compilation-error-on-file-lib-phoenix-token-ex-phoenix-socket-struct-0-is-u

We should create an issue to add in those locations for `_build` and `deps` as ENV vars.

**Comment by joshsmith** [comment]
`mix deps.clean` should work for this.

**Comment by schippada** [comment]
Josh found several abandoned volumes and removed them. Build is now successful for me.

**Comment by joshsmith** [comment]
Glad you're all good now @schippada!
