### ISSUE TITLE
Add featured column for projects

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#250]
We'd like to add and expose a featured column for projects. Can only be set/unset by a site admin.

**Comment by schippada** [comment]
@JoshSmith , both create & update operations are piped through the bearer_auth plug. So, if I add the featured column to the model and update the view, that will be all. Please confirm.

Also, I am assuming that the data type is string for this attribute. Let me know

**Comment by joshsmith** [comment]
@schippada the data type would be `bool`. You'd need to add something to the policy, too.
