### ISSUE TITLE
Ember remote development mode not working

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-api#251]
In the ember app you can run `ember server --environment=remote-development` to run the app without having to run the API. My understanding is that this hasn't been updated since the API migrated to phoenix. I tried running:

`ember server --environment=remote-development`

but am running into a bunch of errors. 

<img width="1430" alt="code_corps___build_a_better_future_" src="https://cloud.githubusercontent.com/assets/5448834/18772197/2fcd0a7e-8102-11e6-9372-9e1e0e6d77e0.png">

Opening this issue to get this working.

**Comment by joshsmith** [comment]
@WenInCode this requires someone with Heroku access to create that server over there. I'm the bottleneck on this one, I think, and updating everything there is going to be a bit time-consuming. Will mark as high priority but realistically will have to circle back after I work through sketching out some API things for the donations work.

Can you use Docker locally in the meantime?

**Comment by joshsmith** [comment]
- [x] Add ENV to the Heroku app
- [x] Setup AWS / S3 CloudFront config
- [x] Change DNS configuration
- [x] Verify it all works with Ember

**Comment by joshsmith** [comment]
Works. 🎉
