### ISSUE TITLE
Add and configure stripe_eventex

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#257]
We'll want to add this library https://github.com/gearnode/stripe_eventex for handling Stripe webhook events.

The path for our webhooks should probably be `/webhooks/stripe`.

For #10.

**Comment by dmvt** [comment]
I don't suggest using this library. It's got very low use, no updates and built in typos (subscibed_events for instance)

```
config :stripe_eventex, subscibed_events: [{"customer.created", Stripe.CustomerCreated},
                                           {"customer.updated", Stripe.CustomerUpdated} ]
```

**Comment by joshsmith** [comment]
@dmvt opt we close this, then? Any recommendations for how we should handle the webhooks in this case?

**Comment by dmvt** [comment]
Yeah. If we need a webhook wrapper, let's add one to Stripity Stripe
