### ISSUE TITLE
In Docker, Phoenix does not wait for database to start up

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#275]
By the time Phoenix tries to connect to the database, the database is not yet up.

Not sure precisely how to fix but Phoenix should be able to try the connection and only run its startup commands when the database is fully available.

**Comment by joshsmith** [comment]
```
web_1            | Running dependency resolution
web_1            | All dependencies up to date
web_1            | ** (Mix) The database for CodeCorps.Repo couldn't be created: FATAL (cannot_connect_now): the database system is starting up
web_1            |
web_1            | 19:12:16.425 [error] GenServer #PID<0.286.0> terminating
web_1            | ** (Postgrex.Error) FATAL (cannot_connect_now): the database system is starting up
web_1            |     (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
web_1            |     (connection) lib/connection.ex:622: Connection.enter_connect/5
web_1            |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
web_1            | Last message: nil
web_1            | State: Postgrex.Protocol
codecorpsapi_web_1 exited with code 1
```

**Comment by joshsmith** [comment]
This looks like it was introduced by moving to latest `postgrex`.

**Comment by joshsmith** [comment]
If someone can reproduce by pulling down and starting with a fresh Docker setup, that would be amazing.

**Comment by fahrradflucht** [comment]
I could NOT reproduce that with a clean setup. Either it's fixed or it is intermittent.

## 

Edit:
I deleted the containers but  kept the images. This time I hit exactly that issue.

**Comment by joshsmith** [comment]
@Fahrradflucht I think the only way this can be fixed is by running a script to check if the pg connection is available. I poked around Docker support forums and didn't find much else useful.

**Comment by manjufy** [comment]
I get the same error.
Here is the way to reproduce it
https://medium.com/@cristiano.codelab/dockerizing-a-phoenix-application-4e62e7888ae8

**Comment by joshsmith** [comment]
@manju16832003 it looks like that link is no longer working.
