### ISSUE TITLE
Write test for slugged route view

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#287]

**Comment by SViccari** [comment]
@JoshSmith When you have the time, could you provide additional details around what you like to see tested? I see the SluggedRouteController has tests to cover the show action and while I'm not certain, it seems the [view](https://github.com/code-corps/code-corps-api/blob/develop/web/views/slugged_route_view.ex) is rendering the equivalent of API docs.

**Comment by joshsmith** [comment]
@SViccari yes, much the same as the other view tests. Historically it has provided some extra help when we're not trying to test _everything_ in the `show`, but do want to test that a field of some sort was added or removed or modified in some way.

Does that make sense?
