### ISSUE TITLE
Add attachment validations

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#289]
For size, type, etc.

**Comment by roryqueue** [comment]
this looks pretty easy, i can take a crack at it. currently looking at applying versions of this: https://github.com/stavro/arc#file-validation to everything in web/uploaders -- is that on the right track?

**Comment by roryqueue** [comment]
ah there's already the function there to check for filetype, it just needs to be extended. i'll see what i can come up with

**Comment by joshsmith** [comment]
@roryqueue sounds good! I'll mark as in progress until you open a PR ref-ing it.

**Comment by joshsmith** [comment]
Outdated since we moved to Cloudinary.
