### ISSUE TITLE
Add not null constraints everywhere needed

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#309]
- [x] `comments` is missing `user_id`, `task_id`
- [x] `organizations` is missing `name`, `description`, `slug`
- [x] `previews` missing `user_id`
- [x] `project_skills` missing `project_id`, `skill_id`
- [x] `projects` missing `organization_id`
- [x] `role_skills` missing `role_id`, `skill_id`
- [x] `slugged_routes` missing `slug`
- [x] `tasks` missing `title`, `state` (which is also missing a default)
- [x] `user_categories` missing `user_id`, `category_id`
- [x] `user_roles` missing `user_id`, `role_id`
- [x] `user_skills` missing `user_id`, `skill_id`

**Comment by asmita005** [comment]
Hello, i would like to contribute.
where do i locate the above files to make changes to them ?

Thanks

**Comment by joshsmith** [comment]
Closed by #310.

**Comment by joshsmith** [comment]
@asmita005 sorry this got jumped on so quickly before I could respond! Any of the other API tasks would be good to work on, though.
