### ISSUE TITLE
Clarify how to access api subdomain on localhost in INSTALLING.md

### ISSUE THREAD

**Issue by fahrradflucht** [code-corps/code-corps-api#313]
The API must be accessed on an `api` subdomain to work properly. [INSTALLING.md](https://github.com/code-corps/code-corps-api/blob/develop/docs/INSTALLING.md#verify-it-worked) doesn't mention how this should be accomplished and just assumes hitting `http://api.localhost:49235/users` would work, which isn't the case unless one makes changes to `/etc/hosts`.

This should be changed to a working solution. The easiest is probably using `api.lvh.me`.

**Comment by joshsmith** [comment]
@Fahrradflucht thanks for this! We'll address ASAP.

Wish there were a way for Docker to write to hosts automagically, but that seems unlikely. This was a nice thing about Vagrant that I miss.

**Comment by vidmantas** [comment]
I didn't do any changes to my hosts, and didn't use lvh.me, but it works just right out of the box: http://take.ms/IEtI5

**Comment by fahrradflucht** [comment]
Is this on Windows?

**Comment by vidmantas** [comment]
Nope, OS X 10.11.6

**Comment by fahrradflucht** [comment]
This is on Chrome? I did a quick test and Chrome seems support (redirect them to just localhost under the hood) localhost subdomains. Safari and Firefox do not though.

## 

Related Internet-Draft: https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-02

**Comment by vidmantas** [comment]
You're right, Firefox/Safari works with lvh.me or hosts changed. However, they were suggesting to download json as a file, not to view, so I'm not sure if this is feasible option for development. However, I agree this is worth mentioning in the INSTALLING doc. I can provide an explanation there as a PR if you want :)

**Comment by joshsmith** [comment]
@vidmantas that sounds more like an issue with MIME type.

After some brief searching, I came upon this, which seems related: https://github.com/json-api/json-api/issues/1048

**Comment by vidmantas** [comment]
As you can see, I've added a note to `INSTALLING.md` about the situation. If you know any better way how to handle it, I would be glad to contribute.

**Comment by joshsmith** [comment]
@vidmantas thank you! Will review soon.
