### ISSUE TITLE
Use Docker for tests on Circle instead of manually building on Circle's container

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#315]
We should be able to discover issues with contributors' local setups if we decide to use Docker to build on Circle instead.

We need to:
- [ ] Find out if this is achievable
- [ ] Make it happen!

**Comment by fahrradflucht** [comment]
Running the tests with docker shouldn't be a challenge.

`docker-compose run test mix test --cover` would setup all dependent containers for the test container and execute the tests. The only gotcha I see with this is that `apiary` would not get created then, which means that any faults that might arise with this could not be detected.

The only workaround for this would be running `docker-compose up` and then running `docker exec codecorpsapi_test_1 mix test --cover` afterwards. This sounds very fragile to me AND has the problem that [Circle doesn't support `exec` without a hack](https://circleci.com/docs/docker/#docker-exec) that sounds even more fragile.

The thing that makes me unsure about this whole approach though is the caching. If the tests should finish quickly caching is necessary but things like the dependency resolving and compiling are part of the issues that this approach is trying to detect and caching would probably sophisticate this.

**Comment by joshsmith** [comment]
Hmm this may very well be more heartache than it's worth at this juncture. I'm not keen on spending time figuring out issues around this and potentially slowing tests significantly when we do already have CI working. In other words, not sure benefit is worth cost right now.
