### ISSUE TITLE
Use exec instead of run for testing

### ISSUE THREAD

**Issue by fahrradflucht** [code-corps/code-corps-api#319]
[USAGE.md](https://github.com/code-corps/code-corps-api/blob/develop/docs/USAGE.md#running-tests) suggests that tests should be executed by running `docker-compose run test mix test`. This creates a new container on every test run ([See the docs](https://docs.docker.com/engine/reference/commandline/run/)). This doesn't make an sense to me because what is the initial `test` container even there for if not for running the tests in it?

I think the tests should be executed by running `docker exec codecorpsapi_test_1 mix test`. This executes the tests in the already running/present container.

I would PR to change this but I'm not sure if @wolverineks had a good reason to suggests the `docker run` workflow.

**Comment by joshsmith** [comment]
@Fahrradflucht I don't think this was intentional. However, I believe that the `test` container auto-exits right now.

Do you need to know the container name to run `exec`?

The container was really just there to group in `MIX_ENV` and separate it some notionally from `web`.

**Comment by fahrradflucht** [comment]
`exec` executes a given command in a given container so you need to know the name.

As far as my testing goes the `test` container doesn't auto-exit.

**Comment by joshsmith** [comment]
@Fahrradflucht you're right, it no longer auto-exits. I can't keep track of all the futzing I've done with compose.

**Comment by joshsmith** [comment]
Closing as we recommend not using Docker.
