### ISSUE TITLE
Refactor tests in project_category_controller_test

### ISSUE THREAD

**Issue by sbatson5** [code-corps/code-corps-api#322]
This repo has great test coverage!  Some of it is slightly redundant at times.  Here we test both the records created and the JSON returned by our API (which are the same):
https://github.com/code-corps/code-corps-api/blob/develop/test/controllers/project_category_controller_test.exs#L97-L103

I think the importance of the controller is to return formatted JSON that our front-end can consume. Can we safely assume that if the payload is correct, then our records have persisted appropriately?

We also have a few instances like this:
https://github.com/code-corps/code-corps-api/blob/develop/test/controllers/project_category_controller_test.exs#L48-L58

I think this is a great candidate for extracting to some sort of helper that is easier to read and reusable by other controller tests

**Comment by sbatson5** [comment]
And this is me volunteering for it too 😛

**Comment by joshsmith** [comment]
@sbatson5 I think that makes sense. It's also important to note that we have view tests. Basically the controller test needs to test not the whole payload, but just that the view renders the expected data back to us.

It really is a matter of isolating what new things have been added to the stack that aren't tested more fully and appropriately at some lower level.

Would be happy to see a PR and evaluate your exact approach here.

**Comment by sbatson5** [comment]
Thanks for the context! I've only worked on a Elixir app that just serves JSON for our front-end, so I've never actually written a view test in Phoenix.

At the very least, I think we can extract some helpers.

**Comment by sbatson5** [comment]
Should be good to close this issue @JoshSmith. Hopefully it counts towards that Hacktoberfest t-shirt 😉
