### ISSUE TITLE
Eliminate the build_payload helpers from controller tests

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#326]
#323 introduced changes to how we build payloads in our tests with a simpler, more coherent `ex_machina` strategy.

We need to replace this in our controller tests.

Should also add information on this into our README.

You should be able to build a payload with relationships, using 

``` elixir
post = insert(:post)
user = insert(:user)
json_payload(:comment, post: post, user: user)
```

**Comment by sbatson5** [comment]
@JoshSmith I'm not sure I 100% follow this issue.  JSONApi has a lot of different ways to implement relationships. Are we ever side loading information (in the `included` array)? When passing information to `json_payload`, how can we determine what is a relationship and what is simply data?

**Comment by joshsmith** [comment]
@begedin can you provide some context?

**Comment by begedin** [comment]
We try to avoid side-loading, so for now, we do not have an instance of doing that. If we start doing it, I believe the strategy can be improved on so we can have an `include` option.

What the example by @JoshSmith above does is it creates a json payload that simply looks like:

``` elixir
%{
  "data" => %{
    "id" => comment.id |> Integer.to_string,
    "type" => "comment",
    "attributes" => %{
      "body" => comment.body,
      "inserted-at" => comment.inserted_at,
      "markdown" => comment.markdown,
      "updated-at" => comment.updated_at
    },
    "relationships" => %{
      "task" => %{
        "data" => %{
          "id" => comment.task_id |> Integer.to_string,
          "type" => "task"
        }
      },
      "user" => %{
        "data" => %{
          "id" => comment.user_id |> Integer.to_string,
          "type" => "user"
        }
      }
    }
  },
  "jsonapi" => %{
    "version" => "1.0"
  }
}
```

**Comment by joshsmith** [comment]
I definitely do not want to be side-loading if at all possible. I think side-loading makes caching, for example (as in HTTP caching) significantly more difficult than simply identifying the relationships.
