### ISSUE TITLE
Add StripeEvent model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#365]
For #258

See https://stripe.com/docs/api#event_object

ATTRIBUTES
- `id string`
- `object string`, value is "event"
- `api_version string` The Stripe API version used to render data. Note: this property is populated for events on or after October 31, 2014.
- `created timestamp`
- `livemode boolean`
- `pending_webhooks` positive integer or zero Number of webhooks yet to be delivered successfully (return a 20x response) to the URLs you’ve specified.
- `request string` ID of the API request that caused the event. If null, the event was automatic (e.g. Stripe’s automatic subscription handling). Request logs are available in the dashboard but currently not in the API. Note: this property is populated for events on or after April 23, 2013.
- `type string` Description of the event: e.g. invoice.created, charge.refunded, etc.

**Comment by dmvt** [comment]
What's the goal of tracking this?

**Comment by joshsmith** [comment]
Don't think this is actually needed.
