### ISSUE TITLE
Create StripePlan model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#367]
For #258

Stripe's docs: https://stripe.com/docs/api#plan_object

Belongs to a `Project` on Code Corps.

ATTRIBUTES
- `stripe_id`, corresponds to `id string`
- `amount` positive integer or zero The amount in cents to be charged on the interval specified
- `created timestamp`
- `name string` Display name of the plan

**Comment by dmvt** [comment]
Will this be tracking subscriptions related to CodeCorps or donation subscriptions on the connected accounts?

**Comment by joshsmith** [comment]
@dmvt this is for donation subscriptions to projects.

**Comment by joshsmith** [comment]
Closed by #383.
