### ISSUE TITLE
Create StripeCustomer model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#368]
For #258 

Customer for the platform (to be copied to the connect account) and customer for the standalone account.

https://stripe.com/docs/api#customer_object

ATTRIBUTES
- `id string`
- `created timestamp`
- `currency string` The currency the customer can be charged in for recurring billing purposes.
- `default_source string` ID of the default source attached to this customer.
- `delinquent boolean` Whether or not the latest charge for the customer’s latest invoice has failed
- `email string`

**Comment by dmvt** [comment]
What do you mean by 'copied to the connected account'?

**Comment by joshsmith** [comment]
@dmvt https://support.stripe.com/questions/connect-publishable-key-error-with-shared-customers

**Comment by joshsmith** [comment]
Closed by #377.
