### ISSUE TITLE
Add User Categories API

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#39]
Part of #26.

This can be split out into multiple issues to reflect the endpoints in the API docs: http://docs.codecorpsapidevelop.apiary.io/#reference/categories
- [ ] Create
- [ ] Filter
- [ ] Retrieve
- [ ] Delete

**Comment by begedin** [comment]
An approach similar to the existing user skill and role skill endpoints can be used here. PRs that have done this:

#78 - Role skills
#74 - User skills

See the changesets there for a demo how how this is done.

**Comment by joshsmith** [comment]
Closed by #118.
