### ISSUE TITLE
Refactor API Blueprint documentation

### ISSUE THREAD

**Issue by amyschools** [code-corps/code-corps-api#393]
Referenced in comment on pull request #386 by @JoshSmith that the documentation needs to be refactored after changeover to Phoenix.

Suggestions so far:
- [ ] Check consistency of requiring both 'id' and 'type' for Resource Identifier

**Comment by joshsmith** [comment]
There are absolutely a number of areas here that need cleaned up. There's some inconsistency in our object usage, places where `id` parameters are used vs not, missing `required`, etc. A solid read-through really needs done.

**Comment by joshsmith** [comment]
Closed by #400.
