### ISSUE TITLE
Add documentation about rebase conflicts when rebasing 

### ISSUE THREAD

**Issue by amyschools** [code-corps/code-corps-api#399]
The squashing.md file doesn't contain any instructions on how to resolve conflicts or troubleshoot if you have previously merged. 
## Subtasks
- [ ] Could also be included in rebase instructional screencast video that @JoshSmith is planning to make?

**Comment by joshsmith** [comment]
@rileytaylor I believe this is also missing from the instructions in the Ember repo (and anywhere else).

I'm wondering if we should maybe have a set of generalized guides broken out from the repositories into its own repo. It seems like we're in a situation where we can get really out of sync across repos.

**Comment by rileytaylor** [comment]
@joshsmith Maybe a 'code-corps-docs' repo or something? I see your point and that's something I was thinking about. Or even more general... Just 'helpful-docs' for anyone anywhere to link to.

**Comment by joshsmith** [comment]
@rileytaylor this could be part of our super-secret code name project, too, eventually. But for now, just `helpful-docs` is probably good enough.

**Comment by rileytaylor** [comment]
@JoshSmith ill start putting together some thoughts and ideas for this.

**Comment by joshsmith** [comment]
@rileytaylor 🙌
