### ISSUE TITLE
Add Users API

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#42]
Part of #26.

This can be split out into multiple issues to reflect the endpoints in the API docs: http://docs.codecorpsapidevelop.apiary.io/#reference/categories
- [x] Create
- [ ] Filter
- [x] Retrieve
- [x] Check email availability
- [x] Check username availability
- [x] Update

I think we should get rid of `/user/` and `/me` endpoints. Let's not map those over and instead use the normal `users/:id`, even for our authenticated user.

**Comment by begedin** [comment]
~~@JoshSmith Is this up to date? From what I can tell, on the development branch, "update", "retrieve" and "create" all work. I clicked those in, but feel free to revert if there's something missing there.~~

Nevermind. I only just figured out we're actually missing some of the fields.
