### ISSUE TITLE
Testing filtering in policy tests

### ISSUE THREAD

**Issue by mackenziehicks** [code-corps/code-corps-api#452]
# Problem

Need to discuss/decide how to test the filter case in the policy tests.  It seems like we may need to introspect each individual record that comes through to decide whether or not that user has permission to view it.  

@begedin would maybe want to ask for Alan's thoughts on this.

**Comment by begedin** [comment]
As discussed, we reconsidered this and decided not to implement index actions at this point. They would only be used for coalesced id requests (getting a list of records specified via a comma-separated list of ids), which can be, in a slightly less performant way, be replaced by a number of show requests.

I did however, talk to alan, and we concluded that there is basically no right way to handle authorization in such an index action. 

Best idea we could think of is
- Index fetches all records specified by ids.
- Authorization is checked on each individual record
- If authorization fails on any of them, we return a 403
- If authorization passes on all of them, we return a 200 with the requested data.
