### ISSUE TITLE
StripePlatformCustomer updates StripeConnectCustomers on update

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#475]
# Problem

- [x] When a `StripePlatformCustomer` is created, it should create `StripeConnectCustomers` on all `StripeAccount`s for which the `User` currently has a `StripeConnectSubscription`.

- [ ] When a `StripePlatformCustomer` is updated, it should update the `StripeConnectCustomers` in its has_many.

**Comment by begedin** [comment]
When does a sprite platform customer update? It's created when a user adds their first card, basically.

I imagine it would update if they change their email in their profile? Not sure if in any other case, unless it's updated by stripe and we get a webhook for it.

**Comment by joshsmith** [comment]
It could be updated by Stripe and we'd get a webhook. For now we will want to respond only to webhooks listed in #370

**Comment by begedin** [comment]
I was working on updating the platform customer when the user email updates and now that I'm in the code, I don't think there's anything on the connect customer TO update.

Locally, the only stripe value we store is `id_from_stripe`.

The other two fields are `stripe_platform_customer_id` and `stripe_connect_account_id` which are our own id fields, unrelated to stripe. 

Do we maybe want to update the customer email anyway, if the user/platform_customer email changes, regardless of us not actually storing that field locally? Was not storing the field locally a mistake?

**Comment by joshsmith** [comment]
We discussed that we should update the email anyway. We still don't need to store locally.

**Comment by begedin** [comment]
As discussed in #501, updating a customer right now can only happen through updating a user and we don't really do that yet, in an way that would warrant a customer update (we do not change the user email yet).

Since #501 is marked low priority, my guess is, this one ought to be labeled that as well? I'm not sure how to handle it without a good amount of conflicts with #501.

**Comment by joshsmith** [comment]
Closed by #501.
