### ISSUE TITLE
StripePlatformCard updates StripeConnectCards on update

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#476]
# Problem

- [x] When a `StripePlatformCard` is created, it should create `StripeConnectCards` on all `StripeAccount`s for which the `User` currently has a `StripeConnectSubscription`.
- [ ] When a `StripePlatformCard` is updated, it should update the `StripeConnectCards` in its has_many.

**Comment by begedin** [comment]
As with customers, we don't really update any of it yet. Maybe this should be marked lower priority?

**Comment by joshsmith** [comment]
@begedin we don't, but we need to respond to Stripe when it does. There are webhooks for this, where a card may become expired, for example. Or fail. Not sure without looking at the docs precisely.

**Comment by begedin** [comment]
A misunderstanding, then. Wasn't clear to me we need to handle a webhook for this. Sorry.

**Comment by joshsmith** [comment]
My mistake. I thought it was implicit from this but never made it explicit anywhere.
