### ISSUE TITLE
User Reset Password

### ISSUE THREAD

**Issue by snewcomer** [code-corps/code-corps-api#498]
# We need to add a process to request and subsequently reset the user password

### These two can be done in parallel

- #728 Create `User.reset_password_changeset/2`
- #729 Add an `AuthToken` model 

### Once #728 and #729 are done, these two can also be done in parallel

- #730 Add `POST /forgot-password` to request a password reset email
- #733 to generate the reset link for the ember app as part of #730
- #731 Add a `POST /reset-password` to perform the actual reset of password

### This last one is purely optional 

- #732 Send notification email with option to do another reset when the process is done, as an additional security measure.

**Comment by begedin** [comment]
@snewcomer any update on this?

Here's how I would approach it:

## Subtasks

### These two can be done in parallel

- #728 Create `User.reset_password_changeset/2`
- #729 Add an `AuthToken` model 

### Once #728 and #729 are done, these two can also be done in parallel

- #730 Add `POST /password_reset` to request a password reset email
- #731 Add a `POST /reset_password` to perform the actual reset of password

**Comment by begedin** [comment]
@snewcomer I've updated the original issue description with more detailed instructions on how to do this. If you're continuing work on this, feel free to assign yourself to individual smaller issues to mark your progress. 

This one is not marked as "in progress", so I'm not sure if your being assigned to it is just accidental.

**Comment by snewcomer** [comment]
@begedin Awesome.  Thanks for the description!  Starting to tackle the ember side right now.
