### ISSUE TITLE
Rewrite docs to specify using stable versions of Docker

### ISSUE THREAD

**Issue by kevinjcliao** [code-corps/code-corps-api#502]
# Problem

Following the steps on building the Docker container on Mac fails when running the current Docker beta. Specifically fails on `mix deps.get`

```
Step 11 : RUN mix local.hex --force &&     mix local.rebar --force &&     mix deps.clean --all &&     mix deps.get
 ---> Running in fa30995482e3
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.signed.

ERROR: Service 'web' failed to build: The command '/bin/sh -c mix local.hex --force &&     mix local.rebar --force &&     mix deps.clean --all &&     mix deps.get' returned a non-zero code: 1
```

Currently running docker-compose on stable to see if it is in fact caused by the fact that I'm running beta.

**Comment by joshsmith** [comment]
I think we need to write something into the docs specifying that you should work from the stable versions of the Docker packages.

**Comment by joshsmith** [comment]
Also clarify that this uses Docker/Compose version 2.
