### ISSUE TITLE
Graphql

### ISSUE THREAD

**Issue by snewcomer** [code-corps/code-corps-api#51]
@JoshSmith Any thoughts on using graphql for the backend instead of rest.  I know a few ppl who have migrated their apps and have found it simplifies their backend significantly.  Basically will eliminate the need to specify all endpoints and the format of each response.  Sort of eliminates the rigidness of the api.  Also, leaving the client in charge of what data it wants reduces the need for api documentation.  Lmk if you want me to explore for the post endpoint.

**Comment by joshsmith** [comment]
I definitely appreciate the thoughtfulness of this idea and know similar people who have seen great success with GraphQL. I don't think, though, that it's the right fit for us right now, so I'm going to close this.

Thanks for speaking up on it.
