### ISSUE TITLE
"read more about how to develop with the API" on INSTALLING.MD links to wrong file

### ISSUE THREAD

**Issue by afsharalex** [code-corps/code-corps-api#515]
"read more about how to develop with the API" on INSTALLING.MD links to:

https://github.com/code-corps/code-corps-api/blob/develop/docs/USAGE.md 

Should be changed to:

https://github.com/code-corps/code-corps-api/blob/develop/USAGE.md

**Extra /docs in URL Path**

OR

Move file to docs folder

**Comment by joshsmith** [comment]
Thanks for submitting! Do you have a moment to submit a PR for this change?

**Comment by afsharalex** [comment]
Yeah no problem, I'm going to come on slack now so we don't clutter with comments.
