### ISSUE TITLE
Docker compose fails (platform: ubuntu trusty)

### ISSUE THREAD

**Issue by schuyler1d** [code-corps/code-corps-api#517]
# Problem

Getting this when running `docker-compose up` step:
```
web_1            | == Compilation error on file lib/phoenix/token.ex ==
web_1            | ** (CompileError) lib/phoenix/token.ex:144: Phoenix.Socket.__struct__/0 is undefined, cannot expand struct Phoenix.Socket
web_1            |     (stdlib) lists.erl:1354: :lists.mapfoldl/3
web_1            | 
web_1            | could not compile dependency :phoenix, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix", update it with "mix deps.update phoenix" or clean it with "mix deps.clean phoenix"
```
Detail the problem here, including any possible solutions.

## References

Progress on: #

**Comment by joshsmith** [comment]
You may want to kill your Docker processes, run `docker-compose run web mix deps.clean --all phoenix`, and re-run `docker-compose up`. The fs seems to have issues sometimes in the Docker environment for reason I haven't yet tracked down.

**Comment by WenInCode** [comment]
If I remember properly, I had that issue and ^ was the solution. Also, if you are running docker beta I highly suggest moving to docker stable. Not sure if we've added that to the README yet.

**Comment by schuyler1d** [comment]
That fixes it.  PR for documenting it (and docker version)
