### ISSUE TITLE
Update seed data with organization memberships

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-api#533]
# Problem
None of the seeded users have organization memberships. If you went to work on something that requires contributor permissions and up. you'll need to manually create/update the organization memberships through the console.

## Subtasks
- [ ] Create organization-membership for the admin user 
- [ ] Create organization-membership for a contributor (maybe the other seeded user)

**Comment by begedin** [comment]
I believe the admin user we have right now is supposed to be a site admin, so we may want to consider leaving out the current users and just add one new user for each role in the organization.

**Comment by joshsmith** [comment]
@begedin I think we should add in site admin both on Ember and API seeds. We'll have flows coming up that will require people seeing how that works.

**Comment by begedin** [comment]
This is out of date, since we're switching to project users.
