### ISSUE TITLE
Elixir.Ecto.ConstraintError: constraint error when attempting to insert struct:

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#535]
https://sentry.io/coderly/code-corps-api-staging/issues/189378539/

```
Elixir.Ecto.ConstraintError: constraint error when attempting to insert struct:

    * unique: organization_memberships_member_id_organization_id_index

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset defined the following constraints:

    * foreign_key: organization_memberships_organization_id_fkey
    * foreign_key: organization_memberships_member_id_fkey
```

**Comment by joshsmith** [comment]
Looks like we likely need to add another unique_constraint in the create changeset here.

**Comment by begedin** [comment]
We need a unique constraint.

However, if that error is happening, that means someone is able to "request membership" on a project twice, which our client should not allow, so we probably have a client bug to.

**Comment by joshsmith** [comment]
We do. That bug is here https://github.com/code-corps/code-corps-ember/issues/824

**Comment by joshsmith** [comment]
@begedin did we fix this?

**Comment by begedin** [comment]
We did not. I do not see a unique constraint on the model changeset.
