### ISSUE TITLE
Handle Stripe invoice.payment_succeeded webhook event

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#537]
# Problem

* We should handle the `invoice.payment_succeeded` event
* We store the invoice in a local table
  
```Elixir
field :amount_due
field :application_fee

field :id_from_stripe
field :charge_id_from_stripe
field :customer_id_from_stripe
field :subscription_id_from_stripe

belongs_to :user # can figure it out through customer
belongs_to :subscription

# any other fields that make sense
```

* we then track the event. tracking should contain a user id

**Comment by begedin** [comment]
I'm not completely sure what's expected here.

Do we store StripeCharge records locally, or is the event considered handled simply by tracking it. As far as I can tell, both Segment and Mixpanel allow direct Stripe integration, so if it's just tracking, we probably don't get much out of implementing it here.

If it's record storing, again, I'm not sure if we gain much by also storing locally, if the only thing we end up doing with it is to send to segment. We can just hook up segment directly.

Really, I could use more information here.

**Comment by begedin** [comment]
@JoshSmith Updated the issue with information from our Slack conversation
