### ISSUE TITLE
Handle events that do not match the environment (livemode) with a 400 response

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#547]
# Problem

Stripe webhook events can be livemode or non-livemode. 

Right now, the production environment handles livemode events only, while the other environments handle non-livemode events only.

However, even if the event is ignored, our API responds to the webhook request with a 204, which Stripes inteprets as "handled, do not send again", since it's in the 2xx range.

I think it's possible we should be sending some other code here, so Stripe keeps resending the event until it hits the correct  environment. Then again, considering each of our environments has a separate set of stripe accounts, I'm not sure. 

I think we should disuss this.

**Comment by joshsmith** [comment]
I think we should be treating these as handled. Technically the correct server did not respond, so it is accurate for that server to respond with a `400` or similar until the server meant to receive that webhook responds.

There should _never_ – except for user error on our part – be a time where we're sending test data to a production server, or live data to a staging/test/dev server.

But never say never, so we should handle this appropriately: if the Stripe environment is not production and we get a `livemode` `true` request, then it should be handled with a `400`, and vice versa.
