### ISSUE TITLE
Issue with organizations table

### ISSUE THREAD

**Issue by green-arrow** [code-corps/code-corps-api#55]
It looks like the organizations table is being defined with nullable columns on `name` and `slug`. In the existing schema, both of these are `NOT NULL` columns. Is this change intentional?

If they should be `NOT NULL`, it will cause some issues with the controller test cases. We'll no longer be able to just `Repo.insert! %Organization{}`, since those fields must have values now. Additionally, the "does not update chosen resource ..." test will fail, because generating a changeset when using a struct with existing data with no params is still a valid changeset.

``` elixir
changeset = Organization.changeset(%{name: "Name", description: "Description"}, %{})
changeset.valid? == true
```

**Comment by joshsmith** [comment]
@green-arrow `name` and `slug` should both be `NOT NULL` and those fields validate as required in the changeset. Do you want to do a fix PR to address?

Thanks for pointing this out!

**Comment by joshsmith** [comment]
@green-arrow let me know if you'd like to take on PR for this or if you want me to. Assign to whomever you'd like.

**Comment by green-arrow** [comment]
@JoshSmith I can take it on, but I probably won't get to it till tomorrow evening

**Comment by joshsmith** [comment]
@green-arrow is this still a valid issue?

**Comment by green-arrow** [comment]
@JoshSmith - I don't see the non-nullable items being added to those columns on the organization table, so I think this is still an issue.

**Comment by joshsmith** [comment]
@green-arrow okay, maybe we'll tackle tonight then.

**Comment by joshsmith** [comment]
Closing in favor of #309.
