### ISSUE TITLE
User being fetched twice during authentication sequence

### ISSUE THREAD

**Issue by DavidAntaramian** [code-corps/code-corps-api#560]
# Problem

The user is fetched from the database first during the call to [`plug Guardian.Plug.LoadResource`](https://github.com/code-corps/code-corps-api/blob/develop/web/router.ex#L26) and then it is fetched again during the call to [`plug CodeCorps.Plug.CurrentUser`](https://github.com/code-corps/code-corps-api/blob/develop/web/router.ex#L34).

It may be possible to alleviate the second call by calling `Guardian.Plug.current_resource(conn)` [here](https://github.com/code-corps/code-corps-api/blob/develop/web/plugs/current_user.ex#L12) in order to fetch the user from the conn instead of from the database.

This will probably need some testing to ensure that `Guardian.Plug.current_resource/1` works as expected.

**Comment by joshsmith** [comment]
@DavidAntaramian: 

> This will probably need some testing to ensure that Guardian.Plug.current_resource/1 works as expected.

Do you mean testing the plug directly? I haven't done this yet, though I had an article about it lying around somewhere.
