### ISSUE TITLE
Add verification to StripeConnectAccount

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#568]
# Problem

We'll need to add properties from the `verification` hash to the `StripeConnectAccount`.

In particular:

- `verification_disabled_reason`
- `verification_due_by`
- `verification_fields_needed` - can format as a list; in Ecto is an `{:array, :string}`

Needs:

- [x] migration
- [x] new model tests
- [x] new fields on the model
- [x] change the update changeset

**Comment by begedin** [comment]
stripity-stripe is going to need to add support for that part of the account payload in https://github.com/code-corps/stripity_stripe/pull/153
