### ISSUE TITLE
Add StripeConnectAccountController.update for handling funds recipient information

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#586]
# Problem

We should add a `handle_update` method into the controller as well as implement `StripeConnectAccountService.update_funds_recipient`. The matched method is a fallback after the two defined in #583 and #583, and performs similarly.

* It takes parameters sent from the client
* Updates the connect account record on stripe
* Updates the record locally.

# To discuss

@JoshSmith 

My guess is, we will want to show validation errors on the client. I believe we already mentioned that, and also mentioned using the verification fields needed array to do so, instead of the typical changeset approach. Would that be correct. It would certainly make the process a bit simpler, but how would the implementation be handled?

Would we still generate a custom changeset and send it back, or would the client parse the fields needed hash? I think it's easier to manage on the client, but I'm not sure.

**Comment by joshsmith** [comment]
@begedin I would think we would need to pass back the `fields_needed` and use that as the basis, considering the extraordinary variation in the countries.

I think some of that can be handled as we circle back. That is not particularly MVP since I know my information is valid.

**Comment by begedin** [comment]
@JoshSmith I think this can be safely closed.

We are basically allowing the funds recipient update as is. The account get's created in the first step (when we just pass in country and tos acceptance) and the step where fill out the details form is actually the update step. Even if it partially fails for some reason, the form will still be visible and usable so this issue doesn't make much sense anymore. 

The way to improve the process would actually be to implement validation for the form, so we know which fields are missing. For that, when we're ready, we can create a different issue.

**Comment by joshsmith** [comment]
Can we create a different issue now @begedin? Closing in meantime.

**Comment by begedin** [comment]
Created #665
