### ISSUE TITLE
Make switch from arc/arc-ecto to manual uploads to AWS

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#598]
# Problem

arc/arc-ecto are reliant on heroku timeout settings, meaning that if a large file takes too long to upload, the whole thing may time out even though it should've succeeded.

Our main issue with not doing it manually is the URL generation process, but looking at the library code that does that is not too complicated.

* User now just posts a file to our server, we maybe set a `photo_uploading` column to true (or not, we can work that out).
* We take the user’s photo and the AWS signed URL in the client and POST to AWS
* AWS kicks off lambda process to convert the files
* When finished, it hits our server with a Unix timestamp, which then sets the `photo` column
* Right now we have things like `aI1z4zUU.jpeg?63650562986`. We’ll write a migration to split at the `?` and just keep the timestamp
* On the view, we generate URLs based on the known paths we have for those images. We can do that in a separate module, called by the view.

## References
https://www.dailydrip.com/topics/elixir/drips/direct-uploads-with-s3-in-a-phoenix-api
https://github.com/ysugimoto/aws-lambda-image

**Comment by joshsmith** [comment]
Done in #672.
