### ISSUE TITLE
Make `stringify_keys` functions from MapUtils private

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#600]
# Problem

`MapUtils.keys_to_string` calls `stringify_keys` internally, to "deep-convert" all map keys into strings. `stringify_keys` should be private, but has been merged in as public.

**Comment by arubis** [comment]
This looks really straightforward, and so is a good way to run through the motions of a first contribution here :) Spec is green on my end; let me know if I'm overstepping at all by adding the spec for `keys_to_string`.
