### ISSUE TITLE
Fix issues with webhooks

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#609]
# Problem

We have some webhooks that are failing or are not processed. Here's a breakdown of things based on state.

We'll need to decide whether we address all of these now and in what priority. Some appear to be needed, most do not.

- 👍  looks good
- ❓ urgent question
- ❔ non-urgent question, probably doesn't need handled
- 🚫  needs fixed

### `processed`
account.updated 👍 
account.external_account.created 👍 

### `unhandled`
plan.created - nothing particularly interesting happens here since we've just created the plan
customer.source.created - likely does not need handled since it comes from us creating a card
customer.created - probably does not need handled
charge.succeeded - probably covered by invoice payment succeeded
invoice.created - probably does not need handled
invoice.payment_succeeded - handled right now, I believe
customer.updated - handled as much as we can now 
application_fee.created - probably does not need handled
customer.subscription.created - likely does not need handled

**Comment by joshsmith** [comment]
@begedin Should we have handlers that explicitly ignore events with a reason that they were ignored? Might be nice to have it documented for why, originally, we had ignored them.

**Comment by begedin** [comment]
You're correct in thinking `invoice.payment_succeeded` is handled
