### ISSUE TITLE
JSON API serializer does not follow official specs for relationships

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#61]
This is what the payload for a slugged route looks like, for example:

``` Javascript
attributes:  {
  "inserted-at": "2016-08-10T14:04:29",
  slug: "test-slug", 
  "updated-at": "2016-08-10T14:04:29"
},
id: "339",
relationships: {
  organization: { data: nil },
  user: { data: nil} }
  type: "slugged-route"
}
```

According to specs, relationships should look like:

``` Javascript
relationships: {
  organizations: { data: { type: "organizations", id: "organization_id" } },
  users: { data: { type: "users", id: "user_id" } }
}
```

**Comment by joshsmith** [comment]
@begedin I think Phoenix chooses singularized route names.

**Comment by snewcomer** [comment]
@JoshSmith do you want the type pluralized to follow the json-api spec??

From the docs:
`def type(_post,_conn), do: "category"`

**Comment by joshsmith** [comment]
@snewcomer no I don't.

From JSON API spec:

> Note: This spec is agnostic about inflection rules, so the value of type can be either plural or singular. However, the same value should be used consistently throughout an implementation.

**Comment by snewcomer** [comment]
@JoshSmith I see, sry.  So Ember Data is able to inflect the model type?

**Comment by joshsmith** [comment]
@snewcomer yeah, Ember Data doesn't seem to care so much, except maybe on relationships. It's possible we have to do some work at the serializer level of Ember, but I prefer it there over the API. It seems like in some cases Ember Data has made assumptions about the JSON API spec that the spec has not made itself.

**Comment by begedin** [comment]
@JoshSmith This should be closable. Basically, we agreed Phoenix is not at fault here. `ember-data` makes assumptions it shouldn't, so we should fix it there. Should we close it?

**Comment by joshsmith** [comment]
Missed this, yes. Closing now.
