### ISSUE TITLE
Update all customer details on all customer.updated webhooks

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#610]
# Problem

In the customer.updated webhook, we only match on email changes right now. We should update based on any update that comes for this webhook, and update all fields that we can.

**Comment by begedin** [comment]
This was actually a `stripity_stripe` bug, which is closed by https://github.com/code-corps/stripity_stripe/pull/181

**Comment by joshsmith** [comment]
I need to review this to see if it works.

**Comment by joshsmith** [comment]
@begedin the initial issue is fixed but I'm renaming this because we don't update customer in all instances, still.

**Comment by begedin** [comment]
After a discussion, we decided we need more information before making the customer process needlessly more complicated. We are closing this issue until there is a actual need to do anything we aren't doing with customers.
