### ISSUE TITLE
Webhook unsetting account information?

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-api#618]
# Problem

What happens if we update an account and receive a webhook that unsets information? Is that okay? This needs some research, discussion, and testing.

**Comment by begedin** [comment]
Just to offer my thoughts on this, considering we're using managed accounts, we should expect no updates outside our own platform, so we should just be ignoring it in most cases. 

The only thing we should accept are changes in the verification-related fields, so I in my opinion, a good approach to handle this would be

* Figure out which fields get updated when Stripe advances the verification process on an account (ex, `verification.fields_needed`, etc.
* Update our `StripeService.StripeConnectAccountService` update from stripe process to only accept those fields.

**Comment by joshsmith** [comment]
This is effectively the issue in #612 and can be closed.
