### ISSUE TITLE
Expand Validators.ProjectCanEnableDonations to also require payments to be fully setup

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#630]
# Problem

We should expand the `Validators.ProjectCanEnableDonations` validator module so it requires the stripe connect account to be fully setup for payments (`transfers_enabled` needs to be `true`)

This is part of code-corps/code-corps-ember#947

## References

Progress on code-corps/code-corps-ember#947

**Comment by joshsmith** [comment]
This is actually already implemented.

**Comment by joshsmith** [comment]
Wrong. We have `charges_enabled` but not `transfers_enabled`. It should have both.
