### ISSUE TITLE
Change permissions against organization to check the organization owner

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#716]
# Problem

The permissions for operations on the organization should check the organization owner now instead of memberships.

**Comment by ignu** [comment]
@JoshSmith so an organization's admin's can no longer update an organization? only the owner?

**Comment by ignu** [comment]
oops, nevermind, I just saw #718

**Comment by ignu** [comment]
(btw, it does feel a little weird that an admin can create an organization they are no longer allowed to update)
