### ISSUE TITLE
Remove organization memberships

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#718]
# Problem

Once migrated and permissions are fully working and tested in the client application, we should remove all organization memberships code from the API.

**Comment by begedin** [comment]
@christopherstyles I see  you mentioned on slack you'd be taking this on. Just wanna make sure you mark it as in progress and assign to yourself, so no one else grabs it.

**Comment by begedin** [comment]
@christopherstyles @JoshSmith Part of this is done in #735, but not all, so heads up on that.
