### ISSUE TITLE
Write module which takes an auth token value and builds an ember app link to reset password

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#733]
# Problem

This could be very simple or relatively complex, but it's worth a separate issue and discussion from #730 

We need a module with a function which takes an auth token value and returns a path to the ember app route where the password can be reset. 

The module does not need to verify the token or anything similar.

## Proposal

This could be relatively simple. We agree on the specific route ember-side and simply make use of the `:code_corps, :site_url` config value to get the base url, then append the route and the value to get something like

```
www.codecorps.org/reset-password/:value
```

We already had similar behavior before we made the switch to stripe managed accounts, but that has since been removed. Either way, the configuration keys are still there.

@JoshSmith Would you agree that this is enough? Please remove the "blocked" and "question" labels if you do.

**Comment by joshsmith** [comment]
@begedin closing, think this is done. Let me know if not.
