### ISSUE TITLE
Discussion: Should a TaskUser have a due date?

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#738]
# Problem

From #667, we initially considered having a `:due_date` field for a task, but have skipped on that while working on that project/feature.

I don't think it makes sense adding it just for the sake of adding it, but this can be a useful issue to discuss how we could use a field like that, or if we even need it.

**Comment by begedin** [comment]
The way I see it, we could use it in several ways.

- the system could send notifications at specific "distances" from the `:due_date`, reminding the user, the task author, etc.
- the system could do something on the `:due_date`

On the other hand, 

- we could do the same thing with `:updated_at`, since that's the date a user was last assigned to this task.

Thoughts?

**Comment by joshsmith** [comment]
I want to avoid doing a due date for awhile, I think, because it seems a little arbitrary for many things. But I'm not yet sure how to do follow-up in that case and ensure tasks are not sat on without progress for awhile.

**Comment by joshsmith** [comment]
@begedin did you want to keep this open or punt until later?

**Comment by begedin** [comment]
I think we can punt it for now. Feels more like something suitable for a wishlist/idealist somewhere, than a github task.
