### ISSUE TITLE
Eliminate or replace all Repo.all calls in controllers

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#75]
We have a lot of places where we call `Repo.all` without thinking twice about the consequences.

We should start cleaning up all instances of these or replacing them with pagination or something that doesn't fetch every single record from the database.

Please make a separate issue for the one you're trying to remove or replace.

**Comment by begedin** [comment]
While we will want pagination on a lot of things, I should emphasize that `Repo.all` isn't the same as `Model.all` in Rails. It's actually more like `Model.where`, so it's not a big deal if we use it. We might continue to use it even with pagination added.

**Comment by venkatd** [comment]
I believe `Repo.all` hits the database. You can think of it is `Repo.execute_and_fetch_results`
