### ISSUE TITLE
Scheme is missing when images are placed into email dynamically from Cloudinary

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#779]
# Problem

The `img`'s `src` in the project user acceptance email (and other emails) will be missing a scheme because Cloudex gives us a URI without a scheme, which may lead to something like this (on OSX) `x-msg://res.cloudinary.com/dtrnlbt7o/image/upload/c_fill,h_500,w_50=
0/RANDOM_STRING`

I don't yet have a good answer for how to approach this, but it's directly affecting users in production today.

**Comment by paulsullivanjr** [comment]
I was delayed getting started but I'm looking into this

**Comment by joshsmith** [comment]
@paulsullivanjr anything else you need from me here?

**Comment by paulsullivanjr** [comment]
@JoshSmith My schedule got a bit busy again but things are calming down. I've looked into this a bit and wonder if we should either always replace x-msg in ImagePresenter with the http or http scheme or if we should pass in an option to this module when we want to do the replacement. Are there any scenarios where we wouldn't want to do the replacement?

**Comment by joshsmith** [comment]
I think we should generally just prefer to provide it with https in this case.

**Comment by ghost** [comment]
This should be a non-issue...
 
 In testing, I end up with "/icons/user_default_large_.png" per "CLOUDFRONT_DOMAIN" not being set. If set to "https://cloud.foo", then  I end up with "https://cloud.foo/icon/user_default_large_.png". So it seems like this issue is, if it still exists, is because the env var is not set in prod.

**Comment by joshsmith** [comment]
Looks like resolved.
