### ISSUE TITLE
Allow null value for User's email

### ISSUE THREAD

**Issue by npendery** [code-corps/code-corps-api#783]
# GitHub integration with private emails

If a non-CC user comments on an issue in GitHub that is connected to a CC task, when that comment syncs to CC, a user will be created in CC for that user. The issue is that GitHub users do not always have their email exposed, so we need to be able to create a user in CC without an email address.

## Subtasks
- [ ]  Add user creation changeset for GitHub webhook to not validate for email address
- [ ]  Confirm Postgres ability to have null values on a unique column

**Comment by npendery** [comment]
Should we just default their email to a CC owned email such as private_github@codecorps.org? We can do this in the changeset to check if their email field is blank, and if so set it to the default email.

**Comment by begedin** [comment]
THis is being done part of #850
