### ISSUE TITLE
Fix reset_password controller action

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#795]
# Problem

The behavior of the `PasswordResetController#reset_password` is buggy.

I'm sorry, my bad. I forgot the controller action was actually already implemented. That being said, not that I had another look at it, it seems like it might need fixing. The implementation seems strange to me.

- It accepts a token, a password and a password confirmation.
- It verifies the token
- It creates a changeset.
- If the changeset is valid, it renders the user email, but **doesn't really alter the user**
- If the changeset is not valid, it renders a 422

This should be corrected to

- It accepts a token, a password and a password confirmation.
- It verifies the token
- It creates a changeset, **passes it into `Repo.update`**
- If the result is an `{:ok, user}`, render the user
- If the result is an `{:error, changeset}`, render validation errors

## Subtasks

- [ ] Make the changes
- [ ] Update the tests

**Comment by snewcomer** [comment]
@begedin @JoshSmith  after we update the user record, do we want to return a jwt token to call simple-auth `authenticate` on the frontend?

**Comment by snewcomer** [comment]
@begedin this comes from this issue where the thought was the user gets logged in after successfully resetting their password?

https://github.com/code-corps/code-corps-ember/issues/1125

**Comment by begedin** [comment]
@snewcomer That's actually a good idea. My initial thought was, user gets an OK response and then they make another request to login (since they ought to still have the email and thew new password). We could technically even do something like

## Original option

- send a reset request
- if it's on OK response, use the email and password to send a login request

## Second option

- send a reset request
- request responds with token in an OK response
- use that token to sign in immediately, no request.

## Third option
- send a reset request
- if it's an OK response, redirect to login route, optionally with email and new password as parameters, to prefill form
- let them submit form

I think second option is clearly superior to the original, but the third just occurred to me. What do you think about that one? I've seen it "in the wild", but I'm not sure what the general preference is.

**Comment by snewcomer** [comment]
@begedin hmmmm.  The third option sounds good as well.  I wonder if it is an workaround for their sites.  Just a total guess though and probably total legit reason, just not sure what it is!  Guessing I just call the create action in the token controller if we go for #2.  Totally up to you though!

**Comment by begedin** [comment]
I'm actually leaning towards option two as well, but I wanted to make a suggestion for the sake of discussion. Option 2 it is, if you're up for it.
