### ISSUE TITLE
Provide default github user for the purposes of github integration

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#800]
# Problem

We can connect projects, tasks and comments to github repositories, issues and comments respectively. There are cases where a create/edit action on CodeCorps triggers the same action on github. In most cases, the user on behalf of whom this is done is the signed in user. 

However, the signed in user might not be connected to github themselves, in which case, our system needs to provide a default, "CodeCorps" user to perform the action with.

We need to implement a way to do this.

## Subtasks
- [ ] Implement a module which provides a default github user
- [ ] Make this module injectable through the config, so we can mock it in tests, if necessary

**Comment by begedin** [comment]
There's a question of how/where we will store this user. Basically, our API itself needs to be able to authorize/connect with github. Once answered, though, the module should be relatively simple to implement, so we can label it as easy, once the question is resolved.

To my knowledge, this has to be a user, not just an auth token for a repo/organization (if the later is even possible), so my guess is, we would have to create some sort of bot user, or the project manager would have to provide it on a per project (later per repo basis).

@JoshSmith Could use your thoughts here.

**Comment by joshsmith** [comment]
I'm guessing this will need to be a bot user in those cases where the user is not on GitHub themselves, with strong encouragement that they create a GitHub account wherever possible.

**Comment by joshsmith** [comment]
Let me know if this unblocks this question.

**Comment by begedin** [comment]
It confirms my guess, but we still need to figure out how to provide it.

From the tips section [here](https://help.github.com/articles/differences-between-user-and-organization-accounts/#personal-user-accounts) it looks like the process is simply to make a github user account, then use it's auth token. Since auth tokens apparently do not expire, we'd just need to make one through some process and use it.

That leaves us with a few questions:

- Do we create a default `CodeCorps.User`, then connect it to github and use that
- Do we just create a user manually, get the auth token for them, and store it locally somehow

Either way, the  module in the description should be relatively simple and injecting data for tests should be the same.

**Comment by begedin** [comment]
@JoshSmith I believe this has changed a good amount. 

I'm not sure we still need a bot user. Either the user doing the action will be connected, so we will propagate it to github on their behalf, or they wont, in which case, our app identity does the propagation. I guess that's the identity we need to somehow expose?

**Comment by begedin** [comment]
@JoshSmith 

I've tested this out and it actually isn't necessary.

When creating a github API request, to, for example, post an issue or a comment, if we authenticate as a user, the author if the issue/comment is the user. 

When doing the same while authenticated as an app installation, the author will bi `%{app_name}[bot]`, so the default user is provided.
