### ISSUE TITLE
Null Name fallback on donation thank you email.

### ISSUE THREAD

**Issue by LennonR** [code-corps/code-corps-api#819]
# Problem

If I donate without being logged in and create an account during the donation process, I won't have a name associated with my account.  So the thank you email looks like this:

<img width="1440" alt="screen shot 2017-06-04 at 3 30 10 pm" src="https://cloud.githubusercontent.com/assets/916139/26764762/61fb4950-493b-11e7-932d-0e4e83d5f6d3.png">

**Comment by begedin** [comment]
## Proposed solution

- in `emails/receipt.html` replace `{{user_first_name}}` with `{{name}}`
- in `lib/codecorps/emails/receipt_email.ex`, add a `get_name/1`, which receives a user and
  - returns `user.first_name`
  - if that is nil, `user.username`
  - if that is nil, `user.email`
- in `lib/codecorps/emails/receipt_email.ex`, in `build_model/3`, replace `user_first_name` with `name`, the value of which is the result of the above function
- update any tests that break by this

**Comment by joshsmith** [comment]
@LennonR how do you feel about the proposed solution above?

**Comment by LennonR** [comment]
@JoshSmith It works.  I'd prefer something like "Hey {{user_first_name or 'there'}}, thanks..."

I feel like it's a bit friendlier than using somebody's email address.  But not a big deal.  Using email is a decent solution.

**Comment by joshsmith** [comment]
I'd prefer this, as well. @begedin can we have that be the fallback if no `first_name`?

**Comment by begedin** [comment]
That's actually a great idea which I did not consider.

## New proposed solution

- in `emails/receipt.html` replace
```Handlebars
<strong>{{user_first_name}}</strong>, thanks for your monthly donation to <a href="{{project_url}}">{{project_title}}</a>.
```
with 

```Handlebars
Hey {{name}}, thanks for your monthly donation to <a href="{{project_url}}">{{project_title}}</a>.
```

- in `lib/codecorps/emails/receipt_email.ex`, add a `get_name/1`, which receives a user and
  - returns `user.first_name`
  - if that is `nil`,  returns a plain `"there"`

- in `lib/codecorps/emails/receipt_email.ex`, in `build_model/3`, replace `user_first_name` with `name`, the value of which is the result of the above function
- update any tests that break by this
- add a test for the case of the user having no first name into `receipt_email_test.exs`

## Note

Not sure about calling the variable `{{name}}`, technically, it's a `{{form_of_address}}` but that term is uncommon to the point where I'm not sure it would make things clearer.

**Comment by joshsmith** [comment]
`{{name}}` seems fine to me.

**Comment by zacck-zz** [comment]
Hey everyone, I'd like to take a crack at this one.

**Comment by joshsmith** [comment]
Hey @zacck! Go for it. Let me know if you need anything from me.

**Comment by zacck-zz** [comment]
@joshsmith  going for it!! 🗡

**Comment by zacck-zz** [comment]
@joshsmith  a review would be nice when you have a moment please. Thank you so much!
