### ISSUE TITLE
Deal with the "unmatched_user" case of a github installation webhook

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#830]
NOTE: OP is mostly out of date. Refer to https://github.com/code-corps/code-corps-api/issues/830#issuecomment-314046480 for the actual requirements and description.

From https://github.com/code-corps/code-corps-ember/issues/1331 :
> `unmatched_user` - when we receive a webhook but there is no such Code Corps user with the given GitHub id. Edge case for now. This should only happen when the installation was initiated on GitHub. We can handle this by asking a user to connect with GitHub after the fact, and in the meantime matching the installation up to that user. Once the user has connected, we can move the status of the installation to initiated_on_github so they can pick a project.

How do we want to do this?. 

The relatively clear part is that, when a user connects with github, we need to see there are any unmatched installations of their in our database.

However, a github installation record in our database has no field which would connect it to a user.

Do we want to

- Add a `github_user_id` field to the `github_app_installations` table
- Fetch a list of github installations for the user from the API, then match any already in our database

I'm not finding an endpoint to do the second option, so the first one might be the only one available. That would mean that, in the case of an unmatched user, the installation needs to be stored with the github user id.

@JoshSmith What do you think?

**Comment by joshsmith** [comment]
Yeah, this is something that I forgot to add in my notes last night. The first is the only workable option I can find. An `installation` _can_ be on a user's account, but an `installation` is not really _related_ to a user except by way of the user who installed it. This is intentional on GitHub's part: a person may leave a company, but they don't want that to mean the `installation` suddenly has to change "ownership". Instead, the `installation` is most typically performed on an organization level, which means anyone in the organization has access.

This is why we may need to rethink the relationships some.

**Comment by begedin** [comment]
@JoshSmith Correct me if I'm wrong, but 

The `Installation::created` payload will have a "sender.id", which is what we currently take as to `github_id` to find the existing `User` by.

Could we not simply add a field to the installation -> `user_github_id` or `sender_id` and store that in the case of no user found.

Then, as a CodeCorps `User` connects with Github, they receive a `github_id`. We use it to see if there are any `GithubAppInstallationRecords` we can connect them to and if there are, associate them with the `User`.

The way I see it, if we use the field to match an installation with an already connected user, then it's no less wrong to use the field to match an installation with a freshly connected user.

If the field is not good enough for one case, it's not good enough for the other. Am I missing something?

**Comment by joshsmith** [comment]
Are your questions already handled now? How out of date is this?

**Comment by begedin** [comment]
I know what I need to do and we have enough things merged for me to tackle this case. I'm not sure it's of highest priority, though, since there is no way it could happen live, considering `code-corps` is our only project.

**Comment by begedin** [comment]
To update:

It is technically possible for someone to install our app straight from github. 

In that case, we will receive a webhook of this happening, and that webhook will contain a "sender", with an "id", which is the `github_id` of a user that performed the installation.

At that point, 2 things are possible.

1. We're lucky and we have a user registered on code corps, already connected to github, with that `github_id`. We already handle this case and simply connect the installation to the user.

2. There is no user with that `github_id` in our database. That means they have either not registered yet, or have registered but did not connect with github. We handle this by storing a `sender_github_id` on the `GithubAppInstallation` itself.

This PR's aim is to perform a later linking of a user with a `GithubAppInstallation`. This means that
every time a user get's a `github_id` assigned to them, we try to find an installation with identical `sender_github_id`. If there is a match, we assign that installation to the user.

#832 should deal with creating associated repos, so the only thing needed to be done here is the linking itself.

**Comment by joshsmith** [comment]
This is still low priority even though it's possible.

**Comment by begedin** [comment]
@JoshSmith This behavior is now actually in. It's been done as part of #858 through #859

The process of connecting a user now is

- assign `github_id` and `github_auth_token` to `user`
- find installations with `sender_github_id` matching user's `github_id`
- associate those installations with user

This is done in a transaction as well, so this is good to close.
