### ISSUE TITLE
Reorganize the GitHub modules

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#831]
# Problem

According to:

![image](https://user-images.githubusercontent.com/1925540/27636214-ac38af76-5c0a-11e7-9866-eab9655b08a6.png)
 
We could move code like the `CodeCorps.Adapters.GithubRepo` to `lib/code_corps/github_repo/adapter.ex`.

That would provide us the namespace of `CodeCorps.GithubRepo.Adapter`. In the place where we use it right now, we could just alias `CodeCorps.GithubRepo` and then call `GithubRepo.Adapter.from_api`, which seams a bit nicer than what we have currently.

**Comment by begedin** [comment]
Looking at this a second time, I'm not sure `GithubRepo` is the root model we should center it around. 

The proposed structure in Phoenix 1.3 should be about splitting the app into separate contexts.

In the case of a `GithubRepo`, it would fall in the context of either a `Project`, or simply `Github`. I think we should delay moving this around until we have a better idea.

**Comment by begedin** [comment]
I'm closing this, since we've switched to 1.3 and need to reconsider it as bounded contexts. Any discussion would make more sense in #863
