### ISSUE TITLE
Ensure repos are created in other cases of app installation event and diff them

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#832]
# Problem

Right now we only create the repos in one instance of the app installation, but we should really be creating them in all of the instances.

We should also do a `diff` process on the repos, meaning the fetched list is considered the authority. We should:

- delete an installation's repos that are not on the list
- create an installation's repos in the list but not present locally
- update an installation's existing repos matched from the list

**Comment by begedin** [comment]
I'm not sure I'm completely clear on this. Could you elaborate?

**Comment by joshsmith** [comment]
@begedin I think this now qualifies as a follow-up issue for #841 given your comment here:

> **Should we fetch and create repos for all paths**, not only the happy one?

I assume this means you understand the reasoning here now? Does the description still need updated?
