### ISSUE TITLE
Handle API error edge case when handling Installation::created event

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#838]
# Problem

`mix dialyzer` reports a bunch of warnings when analyzing `lib/code_corps/github/event/installation.ex`. Most of these are due to us not handling the case of an API error when requesting installation repositories from the github API. 

Not handling this means the code will throw an error and the event will be kept in the "processing" state indefinitely. We should handle this case.

- Add a function clause for an API Error into the module
- Rewrite rest of module to account for that case - result should be event being marked as "errored"

**Comment by joshsmith** [comment]
Closed by #841.
