### ISSUE TITLE
Add in pagination to all endpoints that need it

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#85]
We're missing pagination from a number of endpoints, namely the posts. We should identify the others, and then add pagination to those requests.

**Comment by joshsmith** [comment]
Belongs to #26.

**Comment by joshsmith** [comment]
See this possibility https://github.com/AgilionApps/ja_serializer#pagination

**Comment by noslouch** [comment]
adding pagination to other endpoints is relatively straightforward. As you can see there's more ceremony around seeding the db in dev and test environments than there is in actually adding pagination support to the controller.

**Comment by snewcomer** [comment]
@JoshSmith what other endpoints need it?  I can take one.

**Comment by joshsmith** [comment]
Closed by #165.
