### ISSUE TITLE
Add in post_type filtering to the posts endpoint

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#86]
We don't have any `post_type` filtering on the posts endpoint right now. We need to add that filtering in to our queries for the `index` actions.

**Comment by joshsmith** [comment]
Belongs to #26.

**Comment by snewcomer** [comment]
@JoshSmith is it filter[post_type]="string" in the url?  I can tackle this if so.

**Comment by joshsmith** [comment]
I don't think it's `filter` like that, I think just `?post_type=`. @begedin can you confirm?

**Comment by begedin** [comment]
I honestly can't remember how it was in rails. Ember's URL doesn't include filter, but doesn't necessarily translate to the API. We should see what our rails API is expecting. That's what Ember is providing behind the scene and that's probably what Phoenix should expect to.
