### ISSUE TITLE
Add info about using `api.lvh.me`  in USAGE.md

### ISSUE THREAD

**Issue by vishaldeepak** [code-corps/code-corps-api#866]
Currently `INSTALLING.md` contains this confirmation under [verify it worked](https://github.com/code-corps/code-corps-api/blob/develop/docs/INSTALLING.md#verify-it-worked)

I think its worth mentioning this again in `USAGE.md`. I myself got confused since I read up first on `Installing.md` and setup my project. A few days later I wanted to work on the repo and read up on `Usage.md` and could not get `locahost:4000` to work. 

If this is ok, then I will raise a pull request.

**Comment by joshsmith** [comment]
Sounds good to me! Would be happy to see a PR @vishaldeepak! Thanks for raising it.

**Comment by joshsmith** [comment]
@vishaldeepak I assigned you, but let me know if that won't work for you.
