### ISSUE TITLE
Remove get_source/1 and the :source field from github events

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#874]
# Problem

From the conversation in this issue, we agreed on removing the source field from the event and removing the `get_source` function.

# Old Problem

In the webhooks handler for GitHub, `get_source` just returns "not implemented" right now. Is this supposed to be implemented at some point? I can't remember what this was supposed to do and there are no notes in the code to elucidate it.

**Comment by begedin** [comment]
We discussed a source in the past, but I also cannot recall what it's supposed to be.

Possibly, it should denote if the event was triggered by an action on codecorps or on github, but I'm not sure how to figure that out or if there's value in it. It would presumably have something to do with the `sender` object of the payload, so maybe the intention was even to figure out if the source is an actual user, or our github app? Again, not seeing a value in it for now, though.

Maybe we should consider dropping the field entirely for now and readding it at a later time if necessary? With github, unlike stripe, we can't really go back to re-retrieve old events and handle them, so storing something, whatever it is, when we don't have a real use for it, doesn't really provide value right now.

**Comment by joshsmith** [comment]
I think you're right that it may have been about whether the source was a user or the app, but for now we can remove it until we determine its necessary again.

**Comment by begedin** [comment]
Looking into this

Once a project has been connected to a repo and I create a task for that project/repo...

- with a user connected to github, from CC
  - the payload will have an `"installation"` hash in the root, with an `"id"` key.
  - the payload will have a `"sender"` hash of "type": "User" and information about the connected user

- with a user not connected to github, from CC
  - the payload will have an `"installation"` hash in the root, with an `"id"` key.
  - the payload will have a `"sender"` hash of "type": "Bot" and login in the format of `%{installation_name}[bot]`

- with a github user, from github
  - the payload will have an `"installation"` hash in the root, with an `"id"` key.
  - the payload will have a `"sender"` hash of "type": "User" and information about the connected user

From that, it's not really possible to infer if the event originated from CC, or from Github directly, so there is no value in the `:source` field and `get_sender/1` in that context.

We can set the source to be a `user`, `bot` or `organization`, but there is not much value in that, in the context of an event, that I can see right now, so my vote would be removal of the field until we're sure there is value.

However, there may be value in the function itself, though not where it's defined right now.

I'll create an issue for it - #928
