### ISSUE TITLE
Remove ja_resource from Organisation Controller

### ISSUE THREAD

**Issue by vishaldeepak** [code-corps/code-corps-api#883]
# Problem
Progress on #864. 

Use steps defined in https://github.com/code-corps/code-corps-api/issues/864#issuecomment-325633865, to remove ja_resource from `organisation_controller.ex`

**Comment by begedin** [comment]
Hey @vishaldeepak 

I've created individual issues for all controllers. Since they are uniform in format, I'll close this one in favor of #892
