### ISSUE TITLE
Either create our own style guide or reference existing one

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#91]
Think we should use this as basis:

https://github.com/levionessa/elixir_style_guide

**Comment by roryqueue** [comment]
doesn't look like i have privileges to self-assign or move to 'in progress', but i can take a crack at this one. should be a good intro to the codebase

**Comment by roryqueue** [comment]
making everything compliant with that style guide, that is

**Comment by roryqueue** [comment]
biggest point of nonconformity was on this one: https://github.com/levionessa/elixir_style_guide/blob/master/README.md#modules which I worked on here: https://github.com/roryqueue/code-corps-api/commit/776af5f0a3e782e974278ee44488916240bad23b. the rest is pretty close to perfect but will go by point-by-point later. lmkwyt 🎱

**Comment by joshsmith** [comment]
@roryqueue if you could open as a PR then we can discuss there. Also if we could add to README. Do we have to tell `credo` to use this, too?

**Comment by roryqueue** [comment]
sure, i'll add a commit pointing this out in the readme and open a pr in a bit. looking through the credo source now, it's not clear if you can use it w/ a style guide other than its default

**Comment by joshsmith** [comment]
@roryqueue okay, let me know either way. If that's the case, then we may need to use its style guide. What do you think?

**Comment by roryqueue** [comment]
sure, at quick glance they actually seem compatible anyways, although it looks like neither is exhaustive and each covers areas the other does not

**Comment by roryqueue** [comment]
ah yeah, he specifically references the same guide you mentioned above in the prelude actually: https://github.com/rrrene/elixir-style-guide/blob/master/README.md#prelude

**Comment by joshsmith** [comment]
@roryqueue so it sounds like we should mention that and mention that `credo` enforces it? If you include in that PR, that would help a ton.

**Comment by roryqueue** [comment]
PR here: https://github.com/code-corps/code-corps-api/pull/321

will be afk for a bit now though

**Comment by roryqueue** [comment]
No problem at all, I'm in no great rush :)

**Comment by roryqueue** [comment]
Oops, wrong place to comment (on phone)

**Comment by joshsmith** [comment]
Closed by #347
