### ISSUE TITLE
Add content into issue/comment body during github sync, explaining which unconnected codecorps user created it on codecorps

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#928]
# Problem

From #874, seeing that a task created by a user not connected to github is set to originate from our installation bot, any user viewing it on github would have no information on who actually created the task/comment on codecorps.

I believe we should consider inserting a bit of content into the issue body.

In the case of the source being a bot, we should get the username of the user on codecorps and insert it at the top (or bottom) of an issue. 

Something like `created by CodeCorps User %{username}`. It could even be a link to the user's profile, or to the task itself.

Additionally, when handling a webhook for such an issue coming from github, we should make sure to remove this content as we propagate back into CC.

I'm not sure how strongly I feel about this, but I believe it's something to consider.

**Comment by joshsmith** [comment]
For these we could do:

> Posted by [**joshsmith**](https://www.codecorps.org/joshsmith) from [Code Corps](https://www.codecorps.org/code-corps/code-corps/tasks/1)
>
> ---
>
> The task body starts here

Then we'd match against the "Posted by" "from Code Corps" and horizontal rule and line breaks to remove it on our side? I'm not sure if I have a better way otherwise.
