### ISSUE TITLE
When creating a user from github, merge github info into user info

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#938]
# Problem

In some cases of handling githug `issues` and `issue_comments` webhooks, a user is created using github info. 

Quoting https://github.com/code-corps/code-corps-api/pull/805#issuecomment-329641688

>When users are created on CC because we don't have any matching info from GH:

>- They don't receive a username
>- They don't receive a default_color
>- They don't have an avatar (it's a broken image), although we do have a GitHub avatar they could use
>- Their sign up context is default; this should probably be set to github or github-api instead

We should discuss how to handle this and create a PR

### Initial thoughts

- I agree `context` should be set
- I'm not sure about setting the avatar. Maybe we should have the view fallback to github avatar when serializing instead? No major reason to have two avatar fields client side.
- We should set a default color
- We can easily set a username, or, again, do the serializer fallback approach

**Comment by joshsmith** [comment]
For setting a default username, we could:

- first see if their github username is available on CC
  - if yes, give them that username
  - if no, prefix with `github-`

We would need to increase our username validator limit to 46 chars in that case.

I'm not sure what other alternatives we could go for. Any ideas?

**Comment by joshsmith** [comment]
Setting a default color is straightforward.

**Comment by joshsmith** [comment]
`context` naming: `github-api`? `github-webook`? Something else?

**Comment by joshsmith** [comment]
For the avatar, I think we should actually do two things:

- Create an async process to pull the image from GitHub and upload it to Cloudinary
- Set a fallback to the GitHub avatar (when present) in the serializer

**Comment by joshsmith** [comment]
I would actually consider breaking all of these into separate issues. I'll try to circle back and do that.

**Comment by joshsmith** [comment]
Closing this due to issues tracking each part: #946 #947 #948 #949
