### ISSUE TITLE
When connecting user to github, associate tasks

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#941]
# Problem

At the moment a code corps user is connected to github, there is a good chance there will already be task records on codecorps, associated to github issues associated to the user.

During the connection process, just like we do with installations, we should identify tasks which need to be associated to the newly connected user and associate them.

The tasks that need to be associated, will have already been associated with premade user records containing the newly connected user's github id.

That means, as the user connects, we need to

- find all users with the same `github_id`
- find their tasks
- reassociate those tasks with the newly connected user

Tagging as question because it likely needs more discussion

**Comment by joshsmith** [comment]
I wish I had much more to add to this, but you summed it up pretty well.

Do we currently have any kind of process for merging users who:

- Were signed up on Code Corps but who are belatedly connecting their GitHub account?
- Had issues from GitHub but who are now just signing up for Code Corps, either by signing up with a GitHub account directly, or belatedly connecting after creating their account? (The latter part of this question may just be the first question repeated.)

**Comment by begedin** [comment]
> Were signed up on Code Corps but who are belatedly connecting their GitHub account?

We have a case for associating them with their app installations, but not for tasks and comments. This issue should handle tasks, #942 should handle comments.

> Had issues from GitHub but who are now just signing up for Code Corps by signing up with a GitHub account directly

That option does not exist now. Presumably, if we implement this correctly now, once we do github signup/signin, we will use the behavior provided by this implementation.

> Had issues from GitHub but who are now just signing up for Code Corps by belatedly connecting after creating their account?

This one should be handled through this and #942, since really, the data to process and consolidate will be the same, just the times the data was created at are different.

For the first examle

- cc user 1 signs up
- github user 1 creates bunch of issues on github for a project which is also on codecorps
- cc user 1 connects and github user 1, data needs to get merged

For the second

- github user 1 creates bunch of issues on github for a project which is also on codecorps
- cc user 1 signs up
- cc user 1 connects and github user 1, data needs to get merged

And for the github signup case which we currently do not have

- github user 1 creates bunch of issues on github for a project which is also on codecorps
- cc user 1 signs up as github user 1, data needs to get merged
