### ISSUE TITLE
Change GitHub syncing of tasks/comments to be async

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#952]
# Problem

When tasks and comments are created on Code Corps, we synchronously try to create corresponding issues and comments on GitHub. This means GitHub is completely blocking to any operation that intends to sync to it; if GitHub goes down, then effectively we also go down.

We should instead rethink this to have syncing operations that reach out to GitHub as an asynchronous operation.

Because this is more advanced an operation and will require a more complex UI (indicators that a task is waiting to be created on GitHub, realtime updates of status, etc), we should punt on this until later.

**Comment by begedin** [comment]
I'm having a hard time finding a correct approach here, but the more I think about it, the more it would make sense to introduce some sort of "Persisted Scheduled Job" system.

By that, I mean we use something like `Quantum` as a job scheduler and we actually store jobs to be executed in our database, so if they fail, they can be retried later.

**Comment by joshsmith** [comment]
I think this makes sense considering that we kind of need to approach our service like Circle would theirs: we're essentially a continuous delivery service. This means we have certain jobs to perform depending on all sorts of complex asynchronous behavior. That behavior is not _nearly_ as complex as running tests, etc, but we're going to be managing queues just the same.

**Comment by joshsmith** [comment]
Closing in favor of #1189 which has a more complete discussion there.
