### ISSUE TITLE
Password Reset Error handling

### ISSUE THREAD

**Issue by snewcomer** [code-corps/code-corps-api#961]
# Problem

Phoenix.Token.verify can return `{:error, :expired}` or `{:error, :invalid}`.  Moreover `Guardian.encode_and_sign` can return an `{:error, any}`.  Another error may be `{:error, :missing}` as well.

Thus we need to update the reset controller and associated tests to handle these error cases.

**Comment by joshsmith** [comment]
https://sentry.io/code-corps/code-corps-api/issues/353206921/
