### ISSUE TITLE
Remove markdown restriction because GitHub Issues and Comments may have blank markdown

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#962]
# Problem

GitHub issues and comments can have `markdown` (in terms of our `Task` and `Comment` models) that are blank/empty/nil etc.

We validate `markdown` coming from a user on Code Corps because we don't want to allow for blank task descriptions. This is a contributor experience concern.

I think, however, that we may want to remove the restriction on the API side altogether, and open an issue on the frontend to do that validation only in certain circumstances (from the `/tasks/new` route, for example). This would fix the bug raised in #940.

> NB: this would also prevent future bugs from occurring in new contexts, like the possibility of us adding a task list UI within some future project milestones UI. You may just want to spike out what's needed for a feature without writing the descriptions just yet.

We should also probably see if there are other fields our changesets are validating for other GitHub-related data and verify that GitHub will always return them the way we expect, else open new issues for those.

**Comment by begedin** [comment]
We can lift the `null: false` restriction from the database field (if there is one) and simply perform the validation in the changeset used to update/insert a task on the client, while keeping it out of changesets used to do github sync.
