### ISSUE TITLE
Determine whether we want markdown required for previews

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#965]
# Problem

Our `Task` and `Comment` models have changed to allow `NULL` values for the `markdown` column. We should determine whether we should allow this for the `Preview` model, as well, and what impact this may have on the client.

**Comment by begedin** [comment]
@JoshSmith 

The ember app behavior is currently implemented in such a way that it will not attempt to create a `preview` with `null` as `body`/`markdown`, so from the client app to server interaction perspective, it makes no difference.

From a "using the API  through a 3rd party client" perspective, attempting to create a preview with `null` `body`/`markdown` will result in a 422 and really, the purpose of the preview model is to be used as a tool for task/comment creation, so even there, I'm not seeing the usefulness in removing the restriction.

The potential usefulness I am seeing is in handling the null content in the first place. If we remove the restriction, some of the code on the client can be simplified at the cost of adding preview fetch network request. I'm not sure that's worth the trouble at this point.
