### ISSUE TITLE
Store Github webhook payload as json on the GithubEvent record

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#969]
# Problem

Github doesn't allow us to retrieve already sent webhooks and view their data, so we should store the entire payload as json on the `GithubEvent` itself, so we can recover and retry errored out events.

**Comment by joshsmith** [comment]
It looks like this can be stored with just a `:map` field type in Ecto and in PostgreSQL it will end up being a `jsonb` type.

This needs tested, of course.
