### ISSUE TITLE
Add a `closed_at` to `Task` to track when task is closed

### ISSUE THREAD

**Issue by daveconnis** [code-corps/code-corps-api#979]
# Problem

Add a `closed_at` to `Task` so we can track when a task was closed (i.e. completed).  Could use this in a project's update emails to their donors about what's been done in the past month.

**Comment by joshsmith** [comment]
This would probably mean somewhere in the `changeset` identifying if it's _just_ been closed and use the current timestamp to set the `closed_at`.
