### ISSUE TITLE
Duplicate GitHub account connections can happen for users

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#981]
# Problem

Right now it's possible to connect multiple GitHub accounts to a user. This is due to the fact that an account is connected via a `github_id` field that has no unique index and no validation against duplicates.

We may want to introduce a `GitHubUser` relationship prior to the making this fix, but it should be straightforward to migrate either way.

**Comment by begedin** [comment]
I'd rather do `GithubUser` at a later time. 

Since we discussed the concept of identify provider records/relationships in the past, we may be a bit hasty if we introduce it now, unless we absolutely know if we want those and what they will look like.

As you said, a migration will happen now or later. It will be a matter of creating an equivalent index on the new record.

**Comment by joshsmith** [comment]
The big question here is how we're going to handle this exactly. I assigned a time to this but I didn't write down my reasoning.

Account collision could happen when:

- Creating a new Code Corps account by signing up with GitHub when you've already connected
- Connecting the same GitHub account to a second account on Code Corps

The former _should_ be preventable, in theory, by looking for the relationship, once we build this, and simply signing the user in rather than having a new account get created.

The second scenario is much more difficult. The simplest "solution" to this problem right now is to add an index to `github_id`, add a validation, and add a decent custom error message explaining what went wrong:

> This GitHub account is already connected to another user on Code Corps.

What we really need in the future is a way to be able to initiate a merge of user accounts. This, in theory, can be done by initiating a request from one user to another that is only approvable through a verified email address. Both users would have to confirm the merge (like an escrow) before the merge begins, and then we'd need to identify which account gets ghosted as a result.

This latter part should _not_ be attempted now.

Since the tasks is now more correctly identified as being simpler/smaller in scope, I'm going to reduce the time from 4 to 2 hours.

**Comment by joshsmith** [comment]
@begedin I decided not to take this on since this was self-assigned by you and marked as in progress. But my notes above should help.
