### ISSUE TITLE
Handle cases where webhook handler does not fail with an {:error, atom} tuple.

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#983]
As far as I'm aware, all of our webhook handlers succeed with `{:ok, data}` or `{:error, reason}`, but we should verify this to. The return should always be a two-element tuple, with the first being an `:ok` or `:error`.

The `reason` should also always be an `atom` and that's what our event processing module expects. It takes the reason, converts it using `Atom.to_string/1` and stores it as `failure_reason` into the database.

However, now that I'm thinking about it, there is a possibility that some handlers fail with something else as a reason, for example, a changeset or a github API error payload.

We should take a look at `Event.Issues`, `Event.IssueComment` and `Event.Installation`. If any of the failed transaction cases fail with something other than an `{:error, atom}`, we should add a `case` clause for that specific case and translate it to an `{:error, atom}`. 

For example

```Elixir
case Repo.transaction(multi) do
  {:ok, %{tasks: tasks}} -> {:ok, tasks}
  {:error, :repo, :unmatched_project, _steps} -> {:ok, []}
  {:error, _errored_step, error_response, _steps} -> {:error, error_response}
end
```

becomes

```Elixir
case Repo.transaction(multi) do
  {:ok, %{tasks: tasks}} -> {:ok, tasks}
  {:error, {tasks, failed_changesets}} -> {:error, :task_validation_errors}
  {:error, :repo, :unmatched_project, _steps} -> {:ok, []}
  {:error, _errored_step, error_response, _steps} -> {:error, error_response}
end
```

Note, that the example is at least one identified case where this bug is happening, but there may be more. 

As of right now, if this does happen, the event handling will fail and the event will stay in the "processing" state forever.

**Comment by begedin** [comment]
I went through the code and listed cases

**0 hours**. While technically `InstallationRepositories` performs an insert, the changeset involved has no validations, so it will never return an `{:error, changeset}`. `{:ok, record}` or `{:error, atom}` seem to be the only outcomes.

**1 hour**. The `Installation` webhook includes a step of updating or inserting a `GithubAppInstallation`, which uses a changeset with validations, so there is a chance for an `{:error, changeset}` being returned. `MatchedUser.handle` and `UnmatchedUser.handle` should check their output and convert `{:error, changeset}` into `{:error, :validation_error_on_syncing_installation}`

**1 hour**. The `Issues.do_handle` runs everything in a transaction, so it's a matter of mapping the transaction result. We should add this after the `:repo` case clause of the transaction.

```Elixir
{:error, :task, %Changeset{}, _steps} -> {:error, :validation_errors_on_syncing_task}
```
 
**1 hour**. The `IssueComment.do_handle` behaves in the same way for the task step. It also needs a similar case clause for the comment step. We should add the following after :

```Elixir
{:error, :task, %Changeset{}, _steps} -> {:error, :validation_errors_on_syncing_task}
{:error, :comments, {_records, _changesets}} -> {:error, :validation_errors_on_syncinc_comments}
```

**Comment by begedin** [comment]
An alternative for this would be to simply modify `CodeCorps.GitHub.Event.stop_processing` by adding a clause where the second part of the error tuple is a changeset.

```Elixir
def stop_processing({:error, %Changeset{} = changeset}, %GithubEvent{} = event) do
  changes = %{status: "errored, failure_reason: changeset |> get_reason()}
  event |> Changeset.change(changes) |> Repo.update
end
```

We could then define different clauses for `get_reason` which can, for example, match against the struct type:

```Elixir
defp get_reason(%Changeset{data: %Task{}}), do: :validation_error_on_syncing_task
defp get_reason(%Changeset{data: %Comment{}}), do: :validation_error_on_syncing_comment
defp get_reason(%Changeset{data: %GithubAppInstallation{}}), do: :validation_error_on_syncing_installation
```

I would say this would take about **2 hours in total** and actually takes us more into the direction of replacing these atoms with friendly messages which has been discussed in other places.

It would require adding these clauses, followed by writing tests for `Github.Event` to make sure they work.

I'm actually leaning slightly towards this approach, since

- it makes it easier to later introduce friendly messages
- allows us advanced features such as storing validation errors as this friendly message
- does not take away any flexibility for individual event handlers. They could still remap outcomes internally as necessary.

**Comment by begedin** [comment]
@JoshSmith I attempted to tackle this, but the second approach is not as simple as I thought. There's way too much knowledge `CodeCorps.GitHub.Event` would require in order to properly figure out what the failure reason is.

I'm now leaning towards having each event handler map all it's failures into an `{:error, failure_reason_atom}`.

Anything else would cause too much back and forth.

To not let my work completely go to waste, I went through our code and mapped the potential returs, with the following assumption.

For handlers which use a top level transaction, I changed the error response mapping of the last, catch all step 

Just as an example, here are all potential failure reasons for the `IssueComment` handler.
```Elixir
case Repo.transaction(multi) do
  {:ok, %{comments: comments}} -> {:ok, comments}
  {:error, :repo, :unmatched_project, _steps} -> {:ok, []}
  {:error, _errored_step, error_response, _steps} -> {:error, error_response}
end
```

The first two are special mappings for success, so they should remain as is. If we replace the last one with

```Elixir
{:error, errored_step, error_response, _steps} -> {:error, {errored_step, error_response}}
```

and do so in other such modules as well, the potential returns are (combined with pre-transactional failures):

For the `IssueComment` webhook:

```Elixir
{:error, :unexpected_payload}
{:error, :unexpected_action}
{:error, {:repo, :unmatched_repository}}
{:error, {:issue_user, Changeset.t}}
{:error, {:issue_user, :multiple_users}} 
{:error, {:comment_user, Changeset.t}}
{:error, {:comment_user, :multiple_users}} 
{:error, {:tasks, {task_list, changeset_list}}}
{:error, {:comments, {comment_list, changeset_list}}}
```

For the `Issues` webhook:

```Elixir
{:error, :unexpected_payload}
{:error, :unexpected_action}
{:error, :not_fully_implemented}
{:error, {:repo, :unmatched_repository}}
{:error, {:user, Changeset.t}}
{:error, {:user, :multiple_users}} 
{:error, {:tasks, {task_list, changeset_list}}}
```

For the `Installation` webhook:

```Elixir
{:error, :unexpected_payload}
{:error, :unexpected_action}
{:error, :not_fully_implemented}
{:error, :unexpected_installation_payload}
{:error, :unexpected_user_payload}
{:error, :too_many_unprocessed_installations}
{:error, Changeset.t}
```

For the `InstallationRepositories` webhook:

```Elixir
{:error, :unexpected_action_or_payload}
{:error, :no_installation}
{:error, :unexpected_installation_payload}
{:error, :unexpected_user_payload}
{:error, :unexpected_repo_payload}
```

While yes, we could potentially write a `GitHub.Event` module change which would handle all of these, it would be based on a lot of implicitness and the module having too much knowledge of individual handler modules.

Due to that, I'm thinking we should go back to my first proposal, and try to streamline it a bit.

All handlers should return either an `{:ok, relevant_result_data}` or `{:error, relevant_failure_atom}`. 

Considering such mapping could grow complex, I propose we extract it into a separate module for each webhook.

The handler itself would perform the processing, while the mapper would take the outcome and map it into a proper tuple. We could then test the mapper separately.

The event handling code would look like:

```Elixir
def handle(type, id, payload) do
  with %{} = params <- build_params(type, id, payload),
       {:ok, %GithubEvent{} = event} <- params |> create_event(),
       {:ok, %GithubEvent{status: "processing"} = processing_event} <- event |> Event.start_processing,
       {:ok, _response} <- payload |> process_payload() |> map_response() do
    processing_event |> Event.mark_processed
  else 
    {:error, reason} when is_atom(reason) -> Event.mark_errored(reason)
  end
end
```

This would simplify the code a bit and make it far more explicit. It would also pave a good chunk of the way towards switching `failure_reason` to human-friendly error messages.

It would also make it simpler to further "asynchronize" the code for handling events. An easy future step would be the have the `CodeCorps.GitHub.Webhook.Processor` create the `GithubEvent` record synchronously, then fire the `CodeCorps.GitHub.Webhook.Handler` to asynchronously mark it as `processing`, still asynchronously handle the payload and then mark it as `processed` or `errored`.

In hindsight, a lot of the existing code is written somewhat inconsistently, mainly because we (and in a major part me) were still learning how to deal with these webhooks.

**Comment by joshsmith** [comment]
All makes sense to me. Should we be creating a refactoring issue, as well, that outlines what we need to do to bring consistency to this code – and which modules specifically serve as the Platonic ideals of what we want?

**Comment by begedin** [comment]
I'm not sure a single issue is specific enough.

The way I see it, we should have

- A task for each of the four event handling modules:
  - `Event.Installation` - #1042
  - `Event.InstallationRepositories` - #1043
  - `Event.Issues` - #1044
  - `Event.IssueComment` - #1045

For each of those tasks, the goal is
- all execution paths should end up with either `{:ok, relevant_result_data}` or `{:error, relevant_failure_atom}`

Then, the last task, blocked by the other 4 would be to refactor the event handling code as above.

Unfortunately we do not yet have a module that's a perfect example, but `Issues` and `IssueComment` are closer than the other two.

**Comment by joshsmith** [comment]
@begedin okay can we make a point of discussing this tomorrow morning then?
