### ISSUE TITLE
Replace all timestamps with utc_datetime

### ISSUE THREAD

**Issue by snewcomer** [code-corps/code-corps-api#988]
- [ ] `@timestamps_opts [type: :utc_datetime] in the model file.`

This is a great article explaining the differences.

https://www.amberbit.com/blog/2017/8/3/time-zones-in-postgresql-elixir-and-phoenix/

**Comment by zacck-zz** [comment]
@snewcomer I would like to try this one out any could you  point me to the simplest point to start this from? Thank you!

**Comment by snewcomer** [comment]
@zacck yep have at it!

**Comment by zacck-zz** [comment]
@snewcomer  mind pointing me to the location I would need to implement the changes going through the listed article

**Comment by snewcomer** [comment]
Looks like this can be closed.  `use Timex.Ecto.Timestamps` does the trick already :(

https://github.com/bitwalker/timex_ecto
https://github.com/code-corps/code-corps-api/blob/develop/lib/code_corps/model/model.ex#L18
