### ISSUE TITLE
Move email nil behavior from GitHub.Adapters.User to Account.create_from_github

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#996]
# Problem

At the moment, our github user adapter specifically removes the email key if the value in the github payload is nil. The reasoning behind it is that we do not want to unset the user email from github.

However, this is an "input" validation issue and should not be part of the behavior of an adapter. Instead, it should go into the github user changeset in Accounts.create_from_github

The tests should follow suit as well.

**Comment by joshsmith** [comment]
This is more complex than I thought and I'm going to deprioritize some accordingly.

For example, you can end up with:

```
  8) test find_or_create_user/1 creates user if none is by comment or id association (CodeCorps.GitHub.Event.IssueComment.UserLinkerTest)
     test/lib/code_corps/github/event/issue_comment/user_linker_test.exs:54
     ** (ArgumentError) nil given for :email. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.email)
     code: created_user = Repo.get_by(User, created_attributes)
```

**Comment by joshsmith** [comment]
Feel free to make a case as to why this should be higher priority.

**Comment by begedin** [comment]
This is a refactoring thing, so I'm fine with lowering priority.

As for the error above, that's occurring in the test code, not actual code. We've had similar issues in the actual code, but since the `UserLinker` rewrites, they should not be occurring. Either way, the old solution was, if a function is supposed to retrieve a user by `email`, which is `nil`, then the function just returns `nil`
